apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuerName }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuerName }}
    solvers:
      - http01:
          ingress:
            ingressTemplate:
              metadata:
                annotations:
                  nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.certManager.http01.sslRedirect }}"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "{{ .Values.certManager.http01.sslRedirect }}"
