apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: qr_bill_app
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: qr_bill_app
      tier: frontend
  template:
    metadata:
      labels:
        app: qr_bill_app
        tier: frontend
    spec:
      imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
    {{- end }}
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
