apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: qracun
    tier: frontend
spec:
  selector:
    app: qracun
    tier: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
  type: {{ .Values.frontend.service.type }}
