apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: qracun
    tier: backend
  ports:
    - name: http
      port: {{ .Values.api.service.ports.http.port }}
      targetPort: {{ .Values.api.service.ports.http.targetPort }}
      {{- if eq .Values.api.service.ports.http.type "NodePort" }}
      nodePort: {{ .Values.api.service.ports.http.nodePort }}
      {{- end }}
    - name: grpc
      port: {{ .Values.api.service.ports.grpc.port }}
      targetPort: {{ .Values.api.service.ports.grpc.targetPort}}
  type: {{ .Values.api.service.type }}
