apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: qracun
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: qracun
      tier: frontend
  template:
    metadata:
      labels:
        app: qracun
        tier: frontend
    spec:
      imagePullSecrets:
    {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
    {{- end }}
      containers:
        - name: {{ .Values.frontend.image }}

