{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: {{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMaps.name }}
            - secretRef:
                name: {{ .Values.secrets.name }}
          
{{- end }}
