apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "{{ .Values.ghcr.username }}",
          "password": "{{ .Values.ghcr.password }}",
          "email": "{{ .Values.ghcr.email }}"
        }
      }
    }