apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{- if ne $key "name" }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
