replicaCount: 1

image:
  repository: prometheuscommunity/postgres-exporter
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9187

env:
  datasource:
    DATA_SOURCE_NAME: "postgresql://<user>:<password>@<host>:5432/<dbname>?sslmode=disable"

serviceMonitor:
  enabled: true
  namespace: qracun-test
  interval: 15s
  selector:
    matchLabels:
      app: postgres-exporter
