apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: qracun
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: grpc
      port: 50051
      targetPort: 50051
  type: ClusterIP
