"""init

Revision ID: 0072c3016538
Revises: 4f6290261445
Create Date: 2025-01-26 17:41:25.380594

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0072c3016538'
down_revision = '4f6290261445'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
