"""init

Revision ID: 011d483580e8
Revises: b173c0afa615
Create Date: 2025-01-09 11:03:09.353963

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "011d483580e8"
down_revision = "b173c0afa615"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
