"""init

Revision ID: 018a68befaaa
Revises: 49b8cb66ea93
Create Date: 2025-01-13 13:42:34.981504

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "018a68befaaa"
down_revision = "49b8cb66ea93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
