"""init

Revision ID: 01baadbb3afe
Revises: f42949724ba9
Create Date: 2025-01-09 23:53:24.961871

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '01baadbb3afe'
down_revision = 'f42949724ba9'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
