"""init

Revision ID: 02386d351c43
Revises: 9be6c9bea20e
Create Date: 2025-01-09 01:51:10.887342

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '02386d351c43'
down_revision = '9be6c9bea20e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
