"""init

Revision ID: 02539df60117
Revises: 93f152e5bfa4
Create Date: 2025-10-23 19:04:12.764910

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '02539df60117'
down_revision = '93f152e5bfa4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
