"""init

Revision ID: 027ba081c2b5
Revises: f5a7193a7d8d
Create Date: 2025-01-24 03:22:03.522338

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "027ba081c2b5"
down_revision = "f5a7193a7d8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
