"""init

Revision ID: 0297f84cb45d
Revises: f375e314f886
Create Date: 2024-09-13 19:25:07.203225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0297f84cb45d'
down_revision = 'f375e314f886'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
