"""init

Revision ID: 02ab965b6edd
Revises: 9efb8229c35c
Create Date: 2024-10-29 21:17:41.837369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ab965b6edd'
down_revision = '9efb8229c35c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
