"""init

Revision ID: 02e7cab561d6
Revises: 124c3c9b6da7
Create Date: 2025-01-24 03:07:00.363113

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "02e7cab561d6"
down_revision = "124c3c9b6da7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
