"""init

Revision ID: 0300f81e2c26
Revises: 6ba98c3d1c76
Create Date: 2024-09-13 20:12:04.116639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0300f81e2c26'
down_revision = '6ba98c3d1c76'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
