"""init

Revision ID: 037e1333eecb
Revises: 7825d477b771
Create Date: 2025-11-25 18:56:51.209415

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '037e1333eecb'
down_revision = '7825d477b771'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
