"""init

Revision ID: 03ab34ae540b
Revises: 8b8690a0c7ab
Create Date: 2025-02-01 22:20:26.055795

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '03ab34ae540b'
down_revision = '8b8690a0c7ab'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
