"""init

Revision ID: 03b8fd815839
Revises: 66b1dd689061
Create Date: 2024-10-15 21:13:53.479247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b8fd815839'
down_revision = '66b1dd689061'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
