"""init

Revision ID: 040c02cb7745
Revises: 5e652e50d76f
Create Date: 2025-02-18 14:25:02.387733

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '040c02cb7745'
down_revision = '5e652e50d76f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
