"""init

Revision ID: 041fe12a717a
Revises: 8ba588e5d39e
Create Date: 2025-11-25 16:32:43.984262

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '041fe12a717a'
down_revision = '8ba588e5d39e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
