"""init

Revision ID: 048066d684b0
Revises: a123c06c3294
Create Date: 2025-02-02 00:08:45.502252

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '048066d684b0'
down_revision = 'a123c06c3294'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
