"""init

Revision ID: 04e6c12253d3
Revises: 67f51ac9fb83
Create Date: 2025-11-25 19:25:40.546601

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '04e6c12253d3'
down_revision = '67f51ac9fb83'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
