"""init

Revision ID: 04fac5c0795a
Revises: 51b0b70c3821
Create Date: 2025-02-04 00:45:26.986953

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "04fac5c0795a"
down_revision = "51b0b70c3821"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
