"""init

Revision ID: 05ba6d94a691
Revises: edd4ebed6c5b
Create Date: 2025-01-10 11:10:54.276098

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '05ba6d94a691'
down_revision = 'edd4ebed6c5b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
