"""init

Revision ID: 061e2c9a96de
Revises: b9333414c629
Create Date: 2025-02-07 22:50:54.228195

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "061e2c9a96de"
down_revision = "b9333414c629"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
