"""init

Revision ID: 066ef0a61344
Revises: 154aef3d979e
Create Date: 2025-02-03 23:10:16.069578

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "066ef0a61344"
down_revision = "154aef3d979e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
