"""init

Revision ID: 068b49254c66
Revises: 7a5f80506730
Create Date: 2025-01-24 12:55:35.013396

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '068b49254c66'
down_revision = '7a5f80506730'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
