"""init

Revision ID: 068cde42384c
Revises: 7e8fc2a899f5
Create Date: 2025-01-09 14:53:05.553949

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '068cde42384c'
down_revision = '7e8fc2a899f5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
