"""init

Revision ID: 069ac6528638
Revises: 8544e2690b08
Create Date: 2025-12-23 22:56:43.826927

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '069ac6528638'
down_revision = '8544e2690b08'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
