"""init

Revision ID: 06c85e36afcb
Revises: c670a380df0d
Create Date: 2025-02-09 22:16:02.564676

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "06c85e36afcb"
down_revision = "c670a380df0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
