"""init

Revision ID: 071e8234739a
Revises: 4b99152dac09
Create Date: 2024-09-12 23:14:19.826370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071e8234739a'
down_revision = '4b99152dac09'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
