"""init

Revision ID: 072b1906c384
Revises: c5b6559d5fd0
Create Date: 2025-02-19 00:05:06.261260

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "072b1906c384"
down_revision = "c5b6559d5fd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
