"""init

Revision ID: 073187d337a2
Revises: 79ac9d5d0520
Create Date: 2025-02-03 22:28:11.002286

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "073187d337a2"
down_revision = "79ac9d5d0520"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
