"""init

Revision ID: 07519423e68c
Revises: ccde87c249cc
Create Date: 2025-01-09 17:28:11.390978

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '07519423e68c'
down_revision = 'ccde87c249cc'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
