"""init

Revision ID: 0768fc076f1d
Revises: 0d1dd122273c
Create Date: 2025-01-20 13:44:00.054595

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0768fc076f1d'
down_revision = '0d1dd122273c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
