"""init

Revision ID: 0801f5ceef44
Revises: 9a398dbfb0c5
Create Date: 2025-01-09 00:03:37.742947

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "0801f5ceef44"
down_revision = "9a398dbfb0c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
