"""init

Revision ID: 083609771fe3
Revises: 440f8c0cdad6
Create Date: 2025-01-24 01:27:37.721941

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '083609771fe3'
down_revision = '440f8c0cdad6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
