"""init

Revision ID: 0857cb172899
Revises: 7e9e35ebd8c6
Create Date: 2025-02-02 14:40:20.543151

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0857cb172899'
down_revision = '7e9e35ebd8c6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
