"""init

Revision ID: 08f0b1f4b229
Revises: f0f71caaba5a
Create Date: 2024-09-11 01:04:45.546134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f0b1f4b229'
down_revision = 'f0f71caaba5a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
