"""init

Revision ID: 0962df5794a1
Revises: 06c85e36afcb
Create Date: 2025-02-10 09:42:24.442787

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0962df5794a1'
down_revision = '06c85e36afcb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
