"""init

Revision ID: 09f3f23ad26a
Revises: 5a7f8c1b1041
Create Date: 2025-01-24 00:06:25.703387

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '09f3f23ad26a'
down_revision = '5a7f8c1b1041'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
