"""init

Revision ID: 0a7032c2c13a
Revises: 9d09d4a3dad9
Create Date: 2025-02-08 17:33:23.276104

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "0a7032c2c13a"
down_revision = "9d09d4a3dad9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
