"""init

Revision ID: 0c107ddf492e
Revises: 3918dc358365
Create Date: 2025-01-23 02:58:27.536650

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0c107ddf492e'
down_revision = '3918dc358365'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
