"""init

Revision ID: 0c225ec94cac
Revises: d4f7d97bc6c0
Create Date: 2025-01-23 01:46:30.656611

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "0c225ec94cac"
down_revision = "d4f7d97bc6c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "association_product_category", ["id"])
    op.create_unique_constraint(None, "product", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="unique")
    op.drop_constraint(None, "association_product_category", type_="unique")
    # ### end Alembic commands ###
