"""init

Revision ID: 0cb676c3219a
Revises: f3884d0d02b4
Create Date: 2025-01-25 03:45:55.053013

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "0cb676c3219a"
down_revision = "f3884d0d02b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
