"""init

Revision ID: 0d1dd122273c
Revises: 78b374dffb56
Create Date: 2025-01-20 13:29:49.521935

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "0d1dd122273c"
down_revision = "78b374dffb56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
