"""init

Revision ID: 0d797d97f5a2
Revises: ee13542d8ab8
Create Date: 2025-01-09 23:35:32.874288

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0d797d97f5a2'
down_revision = 'ee13542d8ab8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
