"""init

Revision ID: 0d9354cef347
Revises: c782ce74333b
Create Date: 2025-01-30 23:52:06.462846

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0d9354cef347'
down_revision = 'c782ce74333b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
