"""init

Revision ID: 0d946b301fe8
Revises: bf90592f1e39
Create Date: 2025-11-25 17:29:48.325161

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0d946b301fe8'
down_revision = 'bf90592f1e39'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
