"""init

Revision ID: 0da04b3f55db
Revises: eebd40dc289a
Create Date: 2025-01-23 22:49:33.398177

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0da04b3f55db'
down_revision = 'eebd40dc289a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
