"""init

Revision ID: 0dd34f696263
Revises: 10e954b6ef51
Create Date: 2025-02-10 21:40:06.827138

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0dd34f696263'
down_revision = '10e954b6ef51'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
