"""init

Revision ID: 0ea758e52997
Revises: 10a7ef759083
Create Date: 2025-11-25 17:38:51.681066

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '0ea758e52997'
down_revision = '10a7ef759083'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
