"""init

Revision ID: 0fad94d7e8a3
Revises: bb3c1a020d89
Create Date: 2025-01-25 02:06:11.311656

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "0fad94d7e8a3"
down_revision = "bb3c1a020d89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
