"""init

Revision ID: 0fb4389a682a
Revises: 4bdfdc58d912
Create Date: 2025-01-24 01:19:57.776508

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "0fb4389a682a"
down_revision = "4bdfdc58d912"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
