"""init

Revision ID: 0fdd1ba79e9c
Revises: 6bdcdd53b675
Create Date: 2024-09-13 22:07:40.597910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdd1ba79e9c'
down_revision = '6bdcdd53b675'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
