"""init

Revision ID: 1080576cd74a
Revises: 9b95a114e99a
Create Date: 2025-01-31 20:35:20.581602

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1080576cd74a'
down_revision = '9b95a114e99a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
