"""init

Revision ID: 10847ee3d5d6
Revises: 8dd0367added
Create Date: 2025-01-09 00:18:34.047525

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "10847ee3d5d6"
down_revision = "8dd0367added"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
