"""init

Revision ID: 10a7ef759083
Revises: 0d946b301fe8
Create Date: 2025-11-25 17:31:06.403429

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '10a7ef759083'
down_revision = '0d946b301fe8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
