"""init

Revision ID: 10e954b6ef51
Revises: 628b87e76907
Create Date: 2025-02-10 19:00:42.587947

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '10e954b6ef51'
down_revision = '628b87e76907'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
