"""init

Revision ID: 1143772838ed
Revises: 1afaa091b9b1
Create Date: 2025-11-25 17:54:28.510517

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1143772838ed'
down_revision = '1afaa091b9b1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
