"""init

Revision ID: 121192299fe4
Revises: ff161c9d1cd3
Create Date: 2025-02-10 15:33:52.037600

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "121192299fe4"
down_revision = "ff161c9d1cd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
