"""init

Revision ID: 123f38ad5576
Revises: 9e2e0b714205
Create Date: 2025-02-18 13:57:31.318515

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '123f38ad5576'
down_revision = '9e2e0b714205'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
