"""init

Revision ID: 124c3c9b6da7
Revises: 1fee8108a73b
Create Date: 2025-01-24 03:01:34.230144

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "124c3c9b6da7"
down_revision = "1fee8108a73b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
