"""init

Revision ID: 129cf45c3156
Revises: 616e8f9612f8
Create Date: 2025-02-18 16:12:21.153078

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '129cf45c3156'
down_revision = '616e8f9612f8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
