"""init

Revision ID: 130245c0d700
Revises: 96b93a3809f2
Create Date: 2025-01-25 01:11:49.427149

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "130245c0d700"
down_revision = "96b93a3809f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
