"""init

Revision ID: 13e0d6f00469
Revises: daacce55ad16
Create Date: 2025-02-18 15:19:58.455093

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '13e0d6f00469'
down_revision = 'daacce55ad16'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
