"""init

Revision ID: 14eeea418ce8
Revises: 368ce2242aef
Create Date: 2025-01-09 02:22:49.938871

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "14eeea418ce8"
down_revision = "368ce2242aef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
