"""init

Revision ID: 1531f5ce2d07
Revises: 4c59ca74e3d1
Create Date: 2024-09-11 04:14:41.348235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1531f5ce2d07'
down_revision = '4c59ca74e3d1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
