"""init

Revision ID: 154aef3d979e
Revises: b213d9f45226
Create Date: 2025-02-03 23:05:46.303502

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '154aef3d979e'
down_revision = 'b213d9f45226'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
