"""init

Revision ID: 160ea6488449
Revises: af5809ed5b96
Create Date: 2025-01-21 14:50:52.974725

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '160ea6488449'
down_revision = 'af5809ed5b96'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
