"""init

Revision ID: 1650db12fbe4
Revises: 9057ed79991b
Create Date: 2025-01-20 15:42:59.548232

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1650db12fbe4'
down_revision = '9057ed79991b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
