"""init

Revision ID: 17868764b9ab
Revises: b83f29d82a62
Create Date: 2025-01-23 03:12:21.914914

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "17868764b9ab"
down_revision = "b83f29d82a62"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
