"""init

Revision ID: 1889e96c8fcd
Revises: c2821f85be48
Create Date: 2025-01-09 13:26:48.060378

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1889e96c8fcd'
down_revision = 'c2821f85be48'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
