"""init

Revision ID: 18c1772f2034
Revises: fee8dff2fdc7
Create Date: 2025-02-03 21:50:35.425005

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "18c1772f2034"
down_revision = "fee8dff2fdc7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
