"""init

Revision ID: 18fdbc7f6d7a
Revises: a9725fd03f65
Create Date: 2025-01-24 17:24:33.236933

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '18fdbc7f6d7a'
down_revision = 'a9725fd03f65'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
