"""init

Revision ID: 193fdf3c18f5
Revises: 7e2fcc604589
Create Date: 2024-09-13 20:58:25.310647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193fdf3c18f5'
down_revision = '7e2fcc604589'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
