"""init

Revision ID: 19a6f0340152
Revises: 7d6dbd45a76b
Create Date: 2025-01-25 04:34:16.047029

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "19a6f0340152"
down_revision = "7d6dbd45a76b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
