"""init

Revision ID: 1a1f45d41237
Revises: 92406f42956d
Create Date: 2025-02-04 12:49:12.252270

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1a1f45d41237"
down_revision = "92406f42956d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
