"""init

Revision ID: 1a32382a6b6b
Revises: 68e85d4fba2c
Create Date: 2025-02-10 23:45:44.693803

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1a32382a6b6b"
down_revision = "68e85d4fba2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
