"""init

Revision ID: 1a7257306482
Revises: 1650db12fbe4
Create Date: 2025-01-20 15:45:56.651917

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1a7257306482"
down_revision = "1650db12fbe4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
