"""init

Revision ID: 1a8d63cc4a4d
Revises: 3640f84b5e9b
Create Date: 2024-10-29 15:34:35.950240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8d63cc4a4d'
down_revision = '3640f84b5e9b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
