"""init

Revision ID: 1afaa091b9b1
Revises: 0ea758e52997
Create Date: 2025-11-25 17:47:26.677656

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1afaa091b9b1'
down_revision = '0ea758e52997'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
