"""init

Revision ID: 1b2f9374bfd1
Revises: 3519ed06e773
Create Date: 2025-01-23 03:45:06.223095

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1b2f9374bfd1"
down_revision = "3519ed06e773"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
