"""init

Revision ID: 1b66a6efb354
Revises: 41b859838010
Create Date: 2025-02-09 22:11:05.155089

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1b66a6efb354'
down_revision = '41b859838010'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
