"""init

Revision ID: 1bd2ceafdcdf
Revises: 03ab34ae540b
Create Date: 2025-02-01 22:50:58.005910

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1bd2ceafdcdf'
down_revision = '03ab34ae540b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
