"""init

Revision ID: 1c6bb20114ab
Revises: 8d1644919907
Create Date: 2024-09-13 16:52:59.423281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6bb20114ab'
down_revision = '8d1644919907'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
