"""init

Revision ID: 1cc963ff68c3
Revises: f7d4b60e8b0d
Create Date: 2025-01-23 23:10:17.045248

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1cc963ff68c3"
down_revision = "f7d4b60e8b0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
