"""init

Revision ID: 1d5839bfd3d4
Revises: 7b784582d4c5
Create Date: 2025-01-10 11:26:03.503161

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1d5839bfd3d4'
down_revision = '7b784582d4c5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
