"""init

Revision ID: 1dba4600f574
Revises: 68298c9ac5d6
Create Date: 2025-02-01 23:41:06.163270

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1dba4600f574"
down_revision = "68298c9ac5d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
