"""init

Revision ID: 1f3b9211f66c
Revises: 3e1769fbc855
Create Date: 2025-01-23 23:24:46.252758

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1f3b9211f66c'
down_revision = '3e1769fbc855'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
