"""init

Revision ID: 1f6440d25c44
Revises: 828e2d8fec52
Create Date: 2025-02-04 22:40:33.180880

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1f6440d25c44"
down_revision = "828e2d8fec52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
