"""init

Revision ID: 1fa1c58aaefd
Revises: c8866c155f2c
Create Date: 2025-01-09 00:35:24.218414

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '1fa1c58aaefd'
down_revision = 'c8866c155f2c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
