"""init

Revision ID: 1fee8108a73b
Revises: 95c67b3d97e7
Create Date: 2025-01-24 01:48:55.567004

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "1fee8108a73b"
down_revision = "95c67b3d97e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
