"""init

Revision ID: 200511830eb8
Revises: 2173c4eddaa2
Create Date: 2025-01-10 12:48:03.266119

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '200511830eb8'
down_revision = '2173c4eddaa2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
