"""init

Revision ID: 207c23e9076f
Revises: 67f6a6425219
Create Date: 2024-10-16 11:00:53.218695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207c23e9076f'
down_revision = '67f6a6425219'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
