"""init

Revision ID: 2173c4eddaa2
Revises: c1f8bb738f50
Create Date: 2025-01-10 12:43:49.668133

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2173c4eddaa2'
down_revision = 'c1f8bb738f50'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
