"""init

Revision ID: 218e07d98b86
Revises: 0c107ddf492e
Create Date: 2025-01-23 03:06:59.010250

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "218e07d98b86"
down_revision = "0c107ddf492e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
