"""init

Revision ID: 21bd967b7159
Revises: 551ee6f5f01b
Create Date: 2025-01-24 13:04:31.542879

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "21bd967b7159"
down_revision = "551ee6f5f01b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
