"""init

Revision ID: 21d1eb8cf122
Revises: 048066d684b0
Create Date: 2025-02-02 00:13:36.677071

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '21d1eb8cf122'
down_revision = '048066d684b0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
