"""init

Revision ID: 2209e3ef653c
Revises: 32b52c43f62a
Create Date: 2025-01-23 03:21:09.223922

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "2209e3ef653c"
down_revision = "32b52c43f62a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
