"""init

Revision ID: 22b1f0acfced
Revises: 29f3113d843b
Create Date: 2025-01-08 21:37:50.336716

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "22b1f0acfced"
down_revision = "29f3113d843b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "association_goods_category", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "association_goods_category", type_="unique")
    # ### end Alembic commands ###
