"""init

Revision ID: 22c139bcfcd6
Revises: 1a1f45d41237
Create Date: 2025-02-04 14:16:48.162156

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "22c139bcfcd6"
down_revision = "1a1f45d41237"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
