"""init

Revision ID: 22d68e075a91
Revises: d80eace7193e
Create Date: 2025-02-02 00:31:16.357334

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '22d68e075a91'
down_revision = 'd80eace7193e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
