"""init

Revision ID: 231a58cb157b
Revises: 2d5b6943c9f2
Create Date: 2025-01-14 13:25:11.394569

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '231a58cb157b'
down_revision = '2d5b6943c9f2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
