"""init

Revision ID: 23b9d466bc04
Revises: aaa203953a48
Create Date: 2025-01-09 22:44:34.551203

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "23b9d466bc04"
down_revision = "aaa203953a48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
