"""init

Revision ID: 2432a1ef4f75
Revises: 7cf8a72a1d28
Create Date: 2025-02-10 15:47:38.775739

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2432a1ef4f75'
down_revision = '7cf8a72a1d28'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
