"""init

Revision ID: 2508c69cc3cd
Revises: 10847ee3d5d6
Create Date: 2025-01-09 00:25:11.910948

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "2508c69cc3cd"
down_revision = "10847ee3d5d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
