"""init

Revision ID: 2539540f7564
Revises: f66b3cc0bdd6
Create Date: 2025-02-18 14:19:04.637011

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2539540f7564'
down_revision = 'f66b3cc0bdd6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
