"""init

Revision ID: 2551b379d2d8
Revises: 2fabed164560
Create Date: 2025-02-18 20:46:55.428424

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "2551b379d2d8"
down_revision = "2fabed164560"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
