"""init

Revision ID: 25ca250237bc
Revises: 65fd8c044e17
Create Date: 2025-02-08 17:29:38.729207

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '25ca250237bc'
down_revision = '65fd8c044e17'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
