"""init

Revision ID: 25ef3ff9bf8c
Revises: 8fa2690b6db3
Create Date: 2025-01-23 03:52:18.985210

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '25ef3ff9bf8c'
down_revision = '8fa2690b6db3'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
