"""init

Revision ID: 26af00a9d7d2
Revises: a6c6154bc032
Create Date: 2025-01-24 13:20:48.822153

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "26af00a9d7d2"
down_revision = "a6c6154bc032"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
