"""init

Revision ID: 274bcb096222
Revises: a2a638d9b71b
Create Date: 2025-01-20 15:25:34.745148

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "274bcb096222"
down_revision = "a2a638d9b71b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
