"""init

Revision ID: 276c40012f73
Revises: 62ec5c13cbb2
Create Date: 2024-09-13 19:45:25.897459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276c40012f73'
down_revision = '62ec5c13cbb2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
