"""init

Revision ID: 28661d8a01a8
Revises: 011d483580e8
Create Date: 2025-01-09 13:10:28.884178

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "28661d8a01a8"
down_revision = "011d483580e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
