"""init

Revision ID: 28c8a2b241eb
Revises: 9d052b57c519
Create Date: 2025-01-23 23:45:58.604278

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '28c8a2b241eb'
down_revision = '9d052b57c519'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
