"""init

Revision ID: 29f3113d843b
Revises: b8d5ad3f7243
Create Date: 2025-01-08 21:31:56.359220

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '29f3113d843b'
down_revision = 'b8d5ad3f7243'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_goods_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goods_id', sa.UUID(), nullable=True),
    sa.Column('cat_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_goods_category')
    # ### end Alembic commands ###
