"""init

Revision ID: 2af9d83171c3
Revises: a5f42aa3e2ec
Create Date: 2025-01-10 20:50:34.604055

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2af9d83171c3'
down_revision = 'a5f42aa3e2ec'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
