"""init

Revision ID: 2b2648a40581
Revises: 0f0dc87d029e
Create Date: 2025-11-25 20:47:00.475167

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2b2648a40581'
down_revision = '0f0dc87d029e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
