"""init

Revision ID: 2b2bb4f5e8c1
Revises: 1b2f9374bfd1
Create Date: 2025-01-23 03:47:30.528613

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "2b2bb4f5e8c1"
down_revision = "1b2f9374bfd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
