"""init

Revision ID: 2b9de53e1877
Revises: c24ec49e4cba
Create Date: 2025-02-04 16:56:39.101433

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2b9de53e1877'
down_revision = 'c24ec49e4cba'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
