"""init

Revision ID: 2c1e6916454a
Revises: 7a04bb627b6c
Create Date: 2024-09-12 23:30:29.792016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1e6916454a'
down_revision = '7a04bb627b6c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
