"""init

Revision ID: 2d3a8cc30b52
Revises: f9da39021201
Create Date: 2025-01-21 14:58:07.372505

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2d3a8cc30b52'
down_revision = 'f9da39021201'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
