"""init

Revision ID: 2d5b6943c9f2
Revises: 761d8d0abf6e
Create Date: 2025-01-13 13:46:32.789541

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2d5b6943c9f2'
down_revision = '761d8d0abf6e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
