"""init

Revision ID: 2dd71562d7cb
Revises: b90799f325da
Create Date: 2025-01-24 12:31:31.713470

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "2dd71562d7cb"
down_revision = "b90799f325da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
