"""init

Revision ID: 2ea1402ccea2
Revises: bc402ff58727
Create Date: 2025-01-23 02:04:11.867746

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2ea1402ccea2'
down_revision = 'bc402ff58727'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
