"""init

Revision ID: 2fabed164560
Revises: 129cf45c3156
Create Date: 2025-02-18 16:13:34.240245

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "2fabed164560"
down_revision = "129cf45c3156"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
