"""init

Revision ID: 30b71eeb90be
Revises: c14adab1592b
Create Date: 2025-01-13 12:42:38.116234

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "30b71eeb90be"
down_revision = "c14adab1592b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
