"""init

Revision ID: 317701632ff1
Revises: d9914d9daa9e
Create Date: 2025-02-02 00:01:00.128608

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '317701632ff1'
down_revision = 'd9914d9daa9e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
