"""init

Revision ID: 317f6407c78e
Revises: 0c225ec94cac
Create Date: 2025-01-23 01:52:03.363875

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "317f6407c78e"
down_revision = "0c225ec94cac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
