"""init

Revision ID: 31e5b914cbba
Revises: 6857fcd812b4
Create Date: 2025-01-11 02:27:07.309004

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '31e5b914cbba'
down_revision = '6857fcd812b4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
