"""init

Revision ID: 31fd3ccbb760
Revises: 14eeea418ce8
Create Date: 2025-01-09 02:24:12.441395

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "31fd3ccbb760"
down_revision = "14eeea418ce8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
