"""init

Revision ID: 32b52c43f62a
Revises: aae4d24163d0
Create Date: 2025-01-23 03:20:40.472293

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "32b52c43f62a"
down_revision = "aae4d24163d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
