"""init

Revision ID: 32fd0f6f24af
Revises: 5a4f113be154
Create Date: 2025-02-01 20:35:18.641501

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "32fd0f6f24af"
down_revision = "5a4f113be154"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
