"""init

Revision ID: 33205ef3c005
Revises: 4df8b14fba44
Create Date: 2025-01-24 00:47:52.852378

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '33205ef3c005'
down_revision = '4df8b14fba44'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
