"""init

Revision ID: 343a4f14fbbd
Revises: 59b44214e2ef
Create Date: 2024-09-12 22:14:14.453301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343a4f14fbbd'
down_revision = '59b44214e2ef'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
