"""init

Revision ID: 344e45bdb856
Revises: 276c40012f73
Create Date: 2024-09-13 19:50:18.323924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344e45bdb856'
down_revision = '276c40012f73'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
