"""init

Revision ID: 3467f84fad07
Revises: d1ac82ee129f
Create Date: 2025-01-25 00:38:53.994398

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3467f84fad07"
down_revision = "d1ac82ee129f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
