"""init

Revision ID: 34a69335e3de
Revises: b1394ba55460
Create Date: 2025-01-24 01:03:07.122130

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "34a69335e3de"
down_revision = "b1394ba55460"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
