"""init

Revision ID: 3519ed06e773
Revises: 6f4da2d5df2a
Create Date: 2025-01-23 03:41:43.574431

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3519ed06e773"
down_revision = "6f4da2d5df2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
