"""init

Revision ID: 35a82a9fe4a8
Revises: bada4a8a93f5
Create Date: 2025-01-24 01:11:40.180388

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '35a82a9fe4a8'
down_revision = 'bada4a8a93f5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
