"""init

Revision ID: 35d18bf524e1
Revises: 442d5262891d
Create Date: 2025-02-08 17:51:46.500247

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "35d18bf524e1"
down_revision = "442d5262891d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
