"""init

Revision ID: 3640f84b5e9b
Revises: 8cb12bf4036e
Create Date: 2024-10-29 15:31:33.347111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3640f84b5e9b'
down_revision = '8cb12bf4036e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
