"""init

Revision ID: 3686ba4341b4
Revises: 4af01f3e17d4
Create Date: 2025-11-25 20:04:09.536418

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3686ba4341b4'
down_revision = '4af01f3e17d4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
