"""init

Revision ID: 368ce2242aef
Revises: 8ddd9764843b
Create Date: 2025-01-09 02:17:33.254501

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '368ce2242aef'
down_revision = '8ddd9764843b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
