"""init

Revision ID: 36d1bcee4a1b
Revises: 9b3426fb8d83
Create Date: 2025-10-13 18:08:31.947932

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "36d1bcee4a1b"
down_revision = "9b3426fb8d83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
