"""init

Revision ID: 37a242ef46fa
Revises: 027ba081c2b5
Create Date: 2025-01-24 03:24:09.269983

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '37a242ef46fa'
down_revision = '027ba081c2b5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
