"""init

Revision ID: 37b174202e6f
Revises: fb24783e700f
Create Date: 2025-01-25 00:29:56.562416

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "37b174202e6f"
down_revision = "fb24783e700f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
