"""init

Revision ID: 3918dc358365
Revises: 2ea1402ccea2
Create Date: 2025-01-23 02:56:48.215651

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3918dc358365'
down_revision = '2ea1402ccea2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
