"""init

Revision ID: 392d4be28c89
Revises: 066ef0a61344
Create Date: 2025-02-03 23:23:22.407464

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '392d4be28c89'
down_revision = '066ef0a61344'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
