"""init

Revision ID: 3a398aa40954
Revises: 17868764b9ab
Create Date: 2025-01-23 03:15:59.019830

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3a398aa40954"
down_revision = "17868764b9ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
