"""init

Revision ID: 3a546e215519
Revises: 8c62f2186d79
Create Date: 2024-08-28 20:58:16.420643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a546e215519'
down_revision = '8c62f2186d79'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
