"""init

Revision ID: 3b421e05559c
Revises: 79c1b66330bb
Create Date: 2025-01-10 20:26:09.647011

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3b421e05559c"
down_revision = "79c1b66330bb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bill", sa.Column("image", sa.VARCHAR(length=30000), nullable=True))
    op.drop_column("bill", "picture_path")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bill",
        sa.Column(
            "picture_path", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("bill", "image")
    # ### end Alembic commands ###
