"""init

Revision ID: 3b582490f644
Revises: 970c7e6280cb
Create Date: 2024-09-13 16:46:45.899455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b582490f644'
down_revision = '970c7e6280cb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
