"""init

Revision ID: 3bb5fc0bee33
Revises: 207c23e9076f
Create Date: 2024-10-18 12:50:13.133005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb5fc0bee33'
down_revision = '207c23e9076f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
