"""init

Revision ID: 3c251bea7dba
Revises: f41bcb9cb1d4
Create Date: 2025-01-24 16:23:10.774092

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3c251bea7dba'
down_revision = 'f41bcb9cb1d4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_product_id', sa.UUID(), nullable=True),
    sa.Column('cat_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_product_id'], ['user_product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('association_product_category')
    op.create_unique_constraint(None, 'user_product', ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_product', type_='unique')
    op.create_table('association_product_category',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('cat_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], name='association_product_category_cat_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='association_product_category_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='association_product_category_pkey'),
    sa.UniqueConstraint('id', name='association_product_category_id_key')
    )
    op.drop_table('user_product_category')
    # ### end Alembic commands ###
