"""init

Revision ID: 3c2f1b4a827b
Revises: 2b2648a40581
Create Date: 2025-11-25 20:48:52.044394

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3c2f1b4a827b'
down_revision = '2b2648a40581'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
