"""init

Revision ID: 3cb4161b786c
Revises: ab3258396bd5
Create Date: 2025-01-24 11:59:23.183952

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3cb4161b786c'
down_revision = 'ab3258396bd5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
