"""init

Revision ID: 3cb652104ca8
Revises: 23b9d466bc04
Create Date: 2025-01-09 23:05:22.762100

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3cb652104ca8'
down_revision = '23b9d466bc04'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
