"""init

Revision ID: 3dbcf2bd1e96
Revises: 4f1284e03e97
Create Date: 2024-09-13 21:57:23.055580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbcf2bd1e96'
down_revision = '4f1284e03e97'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
