"""init

Revision ID: 3e1769fbc855
Revises: 7e85052bacfd
Create Date: 2025-01-23 23:22:03.622079

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3e1769fbc855"
down_revision = "7e85052bacfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
