"""init

Revision ID: 3e571551f5c5
Revises: d3d93f30e3c8
Create Date: 2025-02-01 20:52:14.831043

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3e571551f5c5"
down_revision = "d3d93f30e3c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
