"""init

Revision ID: 3ec8a9d87520
Revises: 8bc95bf5f66b
Create Date: 2024-09-13 21:26:36.049513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec8a9d87520'
down_revision = '8bc95bf5f66b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
