"""init

Revision ID: 3ff409b0b020
Revises: bf65d14864a8
Create Date: 2025-01-24 03:30:09.857344

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '3ff409b0b020'
down_revision = 'bf65d14864a8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
