"""init

Revision ID: 417910c62bf1
Revises: a67672dd9a35
Create Date: 2025-01-09 16:27:28.591110

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "417910c62bf1"
down_revision = "a67672dd9a35"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
