"""init

Revision ID: 41b5bd989bc2
Revises: eacf7d653d7e
Create Date: 2025-01-11 04:21:31.046487

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '41b5bd989bc2'
down_revision = 'eacf7d653d7e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
