"""init

Revision ID: 41c25e977908
Revises: 5560436afc5b
Create Date: 2024-09-13 19:17:17.360333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c25e977908'
down_revision = '5560436afc5b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
