"""init

Revision ID: 423678edbcf0
Revises: f10cd42028ae
Create Date: 2025-02-02 01:25:25.735415

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "423678edbcf0"
down_revision = "f10cd42028ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
