"""init

Revision ID: 42909b25e6c2
Revises: eebc766fc380
Create Date: 2025-01-12 13:46:01.368644

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "42909b25e6c2"
down_revision = "eebc766fc380"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
