"""init

Revision ID: 42a413acf375
Revises: 90212d4b5912
Create Date: 2025-01-24 03:14:21.536331

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '42a413acf375'
down_revision = '90212d4b5912'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
