"""init

Revision ID: 42a492e4849c
Revises: 76fd9da56db2
Create Date: 2025-01-10 13:11:53.920826

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '42a492e4849c'
down_revision = '76fd9da56db2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
