"""init

Revision ID: 433cfe1cb060
Revises: d0a11b37c7a2
Create Date: 2025-01-08 22:05:21.061139

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '433cfe1cb060'
down_revision = 'd0a11b37c7a2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
