"""init

Revision ID: 436e72bb2e5b
Revises: bb720eec2366
Create Date: 2025-02-01 21:10:41.664334

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "436e72bb2e5b"
down_revision = "bb720eec2366"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
