"""init

Revision ID: 439be8eeee1e
Revises: a5c4f4b8b5bf
Create Date: 2025-01-12 02:50:13.182743

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '439be8eeee1e'
down_revision = 'a5c4f4b8b5bf'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
