"""init

Revision ID: 440f8c0cdad6
Revises: 9394495c154e
Create Date: 2025-01-24 01:26:04.161814

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "440f8c0cdad6"
down_revision = "9394495c154e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
