"""init

Revision ID: 442d5262891d
Revises: e43f4f723de7
Create Date: 2025-02-08 17:49:42.806109

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "442d5262891d"
down_revision = "e43f4f723de7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
