"""init

Revision ID: 457598a6e8dc
Revises: 9d7a77d31571
Create Date: 2025-01-12 03:33:01.572597

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '457598a6e8dc'
down_revision = '9d7a77d31571'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
