"""init

Revision ID: 475a6a9b1412
Revises: dc8d91bc5d8d
Create Date: 2025-01-20 15:32:36.251121

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '475a6a9b1412'
down_revision = 'dc8d91bc5d8d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
