"""init

Revision ID: 477108f4f6ed
Revises: 8f740b3d68d9
Create Date: 2025-02-04 16:08:08.401144

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '477108f4f6ed'
down_revision = '8f740b3d68d9'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
