"""init

Revision ID: 47c1ff3b9c56
Revises: 1dba4600f574
Create Date: 2025-02-01 23:49:24.097656

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '47c1ff3b9c56'
down_revision = '1dba4600f574'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
