"""init

Revision ID: 48524b77b159
Revises: 1080576cd74a
Create Date: 2025-01-31 20:45:55.058616

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '48524b77b159'
down_revision = '1080576cd74a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
