"""init

Revision ID: 4868861f4fa9
Revises: e09b3803ed26
Create Date: 2025-02-02 00:36:27.108485

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4868861f4fa9'
down_revision = 'e09b3803ed26'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
