"""init

Revision ID: 488afbd92edc
Revises: ac6585a1ed97
Create Date: 2024-09-12 22:51:10.721924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488afbd92edc'
down_revision = 'ac6585a1ed97'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
