"""init

Revision ID: 48b713fc434e
Revises: 6bff9d2aea65
Create Date: 2025-01-24 21:31:09.799019

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '48b713fc434e'
down_revision = '6bff9d2aea65'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
