"""init

Revision ID: 49b8cb66ea93
Revises: 6a1768538ff8
Create Date: 2025-01-13 12:56:03.870717

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '49b8cb66ea93'
down_revision = '6a1768538ff8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
