"""init

Revision ID: 49e0eb13f4a1
Revises: e2539bf65d0e
Create Date: 2025-02-01 23:09:51.320238

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "49e0eb13f4a1"
down_revision = "e2539bf65d0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
