"""init

Revision ID: 4a304862e77d
Revises: 061e2c9a96de
Create Date: 2025-02-08 12:04:31.468158

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4a304862e77d'
down_revision = '061e2c9a96de'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
