"""init

Revision ID: 4a96b0c91759
Revises: 69a6380ec5ed
Create Date: 2025-02-04 01:07:44.625650

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4a96b0c91759'
down_revision = '69a6380ec5ed'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
