"""init

Revision ID: 4af01f3e17d4
Revises: 04e6c12253d3
Create Date: 2025-11-25 19:39:30.919964

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4af01f3e17d4'
down_revision = '04e6c12253d3'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
