"""init

Revision ID: 4b99152dac09
Revises: 6115858ec3f4
Create Date: 2024-09-12 23:13:09.151490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b99152dac09'
down_revision = '6115858ec3f4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
