"""init

Revision ID: 4bdfdc58d912
Revises: fdf45c5ac25b
Create Date: 2025-01-24 01:19:01.370176

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4bdfdc58d912'
down_revision = 'fdf45c5ac25b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
