"""init

Revision ID: 4c0dc094f8b9
Revises: 18c1772f2034
Create Date: 2025-02-03 21:54:14.847604

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "4c0dc094f8b9"
down_revision = "18c1772f2034"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
