"""init

Revision ID: 4c4f728cfdc9
Revises: fb92d1649a89
Create Date: 2025-02-10 15:43:28.153020

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "4c4f728cfdc9"
down_revision = "fb92d1649a89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
