"""init

Revision ID: 4c59ca74e3d1
Revises: ff88cd94f99b
Create Date: 2024-09-11 04:01:11.000856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c59ca74e3d1'
down_revision = 'ff88cd94f99b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
