"""init

Revision ID: 4c7c4ff5c81c
Revises: 3ec8a9d87520
Create Date: 2024-09-13 21:29:19.227630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7c4ff5c81c'
down_revision = '3ec8a9d87520'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
