"""init

Revision ID: 4c9cb7a9e77a
Revises: d61a59297f64
Create Date: 2025-02-01 21:58:15.911338

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4c9cb7a9e77a'
down_revision = 'd61a59297f64'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
