"""init

Revision ID: 4df8b14fba44
Revises: 5e136417802e
Create Date: 2025-01-24 00:45:46.147636

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "4df8b14fba44"
down_revision = "5e136417802e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
