"""init

Revision ID: 4f1284e03e97
Revises: 82097cd64242
Create Date: 2024-09-13 21:39:14.188771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1284e03e97'
down_revision = '82097cd64242'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
