"""init

Revision ID: 4f6290261445
Revises: b0e51725c398
Create Date: 2025-01-26 17:39:58.135459

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "4f6290261445"
down_revision = "b0e51725c398"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
