"""init

Revision ID: 51780c1da6f0
Revises: 817c0110ed5c
Create Date: 2024-12-24 17:51:46.069842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51780c1da6f0'
down_revision = '817c0110ed5c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
