"""init

Revision ID: 51861868a959
Revises: 9fbfa0242495
Create Date: 2025-10-07 09:50:20.893676

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '51861868a959'
down_revision = '9fbfa0242495'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
