"""init

Revision ID: 51b0b70c3821
Revises: 5b38d55f38f2
Create Date: 2025-02-04 00:33:29.110242

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "51b0b70c3821"
down_revision = "5b38d55f38f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
