"""init

Revision ID: 51fbd0fcda9e
Revises: 74a505b43e82
Create Date: 2025-02-01 17:56:56.894024

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "51fbd0fcda9e"
down_revision = "74a505b43e82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login_link", sa.Column("link_uuid", sa.UUID(), nullable=False))
    op.add_column(
        "login_link", sa.Column("link_for", sa.VARCHAR(length=5), nullable=True)
    )
    op.drop_column("login_link", "link")
    op.add_column("users", sa.Column("mail_verified", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("tg_verified", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("password_salt", sa.VARCHAR(length=24), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_salt")
    op.drop_column("users", "tg_verified")
    op.drop_column("users", "mail_verified")
    op.add_column(
        "login_link",
        sa.Column("link", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("login_link", "link_for")
    op.drop_column("login_link", "link_uuid")
    # ### end Alembic commands ###
