"""init

Revision ID: 52284a828a09
Revises: a652afbbb19a
Create Date: 2024-09-12 21:53:31.449888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52284a828a09'
down_revision = 'a652afbbb19a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
