"""init

Revision ID: 53a641ad877a
Revises: be27e2b088b5
Create Date: 2025-02-02 01:00:01.143725

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "53a641ad877a"
down_revision = "be27e2b088b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
