"""init

Revision ID: 544d9f3cc158
Revises: 89488db2aa59
Create Date: 2025-01-13 11:55:59.798033

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '544d9f3cc158'
down_revision = '89488db2aa59'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'image',
               existing_type=sa.VARCHAR(length=30000),
               type_=sa.VARCHAR(length=100000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'image',
               existing_type=sa.VARCHAR(length=100000),
               type_=sa.VARCHAR(length=30000),
               existing_nullable=True)
    # ### end Alembic commands ###
