"""init

Revision ID: 548f7ce2a2e7
Revises: 1915baf31167
Create Date: 2024-09-13 20:07:29.166337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548f7ce2a2e7'
down_revision = '1915baf31167'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
