"""init

Revision ID: 54cff6794dd2
Revises: 22b1f0acfced
Create Date: 2025-01-08 21:47:30.130452

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '54cff6794dd2'
down_revision = '22b1f0acfced'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
