"""init

Revision ID: 551ee6f5f01b
Revises: 068b49254c66
Create Date: 2025-01-24 13:01:59.359951

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "551ee6f5f01b"
down_revision = "068b49254c66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
