"""init

Revision ID: 5560436afc5b
Revises: 3be99d9a80b7
Create Date: 2024-09-13 19:13:51.603773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5560436afc5b'
down_revision = '3be99d9a80b7'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
