"""init

Revision ID: 56df49218229
Revises: e7e6b7f24d9b
Create Date: 2025-09-25 09:16:59.240408

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '56df49218229'
down_revision = 'e7e6b7f24d9b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
