"""init

Revision ID: 57396a5dcacf
Revises: 02ab965b6edd
Create Date: 2024-10-29 21:23:13.194936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57396a5dcacf'
down_revision = '02ab965b6edd'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
