"""init

Revision ID: 5763ba2e4755
Revises: 6c120d5b4057
Create Date: 2024-09-13 22:17:14.066113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5763ba2e4755'
down_revision = '6c120d5b4057'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
