"""init

Revision ID: 5776738367ae
Revises: cbb840987dca
Create Date: 2024-09-12 21:44:46.306694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5776738367ae'
down_revision = 'cbb840987dca'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
