"""init

Revision ID: 57b4d44bb11f
Revises: 78cd9be1043d
Create Date: 2024-09-13 19:01:38.651454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b4d44bb11f'
down_revision = '78cd9be1043d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
