"""init

Revision ID: 5950d629e904
Revises: f93134c82a6a
Create Date: 2025-02-10 16:17:16.823943

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "5950d629e904"
down_revision = "f93134c82a6a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
