"""init

Revision ID: 59b44214e2ef
Revises: de1d7d12f4c1
Create Date: 2024-09-12 22:09:11.038734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b44214e2ef'
down_revision = 'de1d7d12f4c1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
