"""init

Revision ID: 5a2e8ede4785
Revises: 457598a6e8dc
Create Date: 2025-01-12 03:34:45.289912

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5a2e8ede4785'
down_revision = '457598a6e8dc'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
