"""init

Revision ID: 5a4f113be154
Revises: 51fbd0fcda9e
Create Date: 2025-02-01 20:15:09.606992

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5a4f113be154'
down_revision = '51fbd0fcda9e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
