"""init

Revision ID: 5a7f8c1b1041
Revises: 70b585e9a0b7
Create Date: 2025-01-23 23:58:56.041055

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "5a7f8c1b1041"
down_revision = "70b585e9a0b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
