"""init

Revision ID: 5ac500f3aed6
Revises: b9a7e306934f
Create Date: 2025-01-09 13:33:16.522561

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5ac500f3aed6'
down_revision = 'b9a7e306934f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
