"""init

Revision ID: 5b38d55f38f2
Revises: c67ff4fecb9d
Create Date: 2025-02-03 23:59:55.337486

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5b38d55f38f2'
down_revision = 'c67ff4fecb9d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
