"""init

Revision ID: 5b72d1df9264
Revises: 04596d9fc790
Create Date: 2025-02-10 17:02:11.164835

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "5b72d1df9264"
down_revision = "04596d9fc790"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
