"""init

Revision ID: 5e136417802e
Revises: 09f3f23ad26a
Create Date: 2025-01-24 00:12:17.503574

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5e136417802e'
down_revision = '09f3f23ad26a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
