"""init

Revision ID: 5e652e50d76f
Revises: dd077bd4390e
Create Date: 2025-02-18 14:23:16.610984

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "5e652e50d76f"
down_revision = "dd077bd4390e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
