"""init

Revision ID: 5e83c506d8d1
Revises: e213bfab7a8b
Create Date: 2025-01-11 03:41:10.622558

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5e83c506d8d1'
down_revision = 'e213bfab7a8b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
