"""init

Revision ID: 5f91c7ae89f9
Revises: 651cef1e8cf6
Create Date: 2025-02-05 22:54:20.094308

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "5f91c7ae89f9"
down_revision = "651cef1e8cf6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
