"""init

Revision ID: 60dc6346385c
Revises: cac219bb7da2
Create Date: 2025-01-31 00:02:04.702256

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "60dc6346385c"
down_revision = "cac219bb7da2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
