"""init

Revision ID: 6115858ec3f4
Revises: cc7102bb334b
Create Date: 2024-09-12 23:06:31.047667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6115858ec3f4'
down_revision = 'cc7102bb334b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
