"""init

Revision ID: 616e8f9612f8
Revises: bc0fe551b78f
Create Date: 2025-02-18 16:11:17.101418

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "616e8f9612f8"
down_revision = "bc0fe551b78f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
