"""init

Revision ID: 62ec5c13cbb2
Revises: 0297f84cb45d
Create Date: 2024-09-13 19:29:09.868065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ec5c13cbb2'
down_revision = '0297f84cb45d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
