"""init

Revision ID: 640a9f6e941d
Revises: 7e613f7e5189
Create Date: 2025-01-31 18:19:46.895256

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '640a9f6e941d'
down_revision = '7e613f7e5189'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
