"""init

Revision ID: 649ee559359f
Revises: 3dbcf2bd1e96
Create Date: 2024-09-13 22:00:18.791944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649ee559359f'
down_revision = '3dbcf2bd1e96'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
