"""init

Revision ID: 64caef856de8
Revises: c4ccf814e553
Create Date: 2025-02-10 18:11:30.905331

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '64caef856de8'
down_revision = 'c4ccf814e553'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
