"""init

Revision ID: 651cef1e8cf6
Revises: 1f6440d25c44
Create Date: 2025-02-05 13:17:47.556794

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '651cef1e8cf6'
down_revision = '1f6440d25c44'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_verified')
    # ### end Alembic commands ###
