"""init

Revision ID: 65fd8c044e17
Revises: 4a304862e77d
Create Date: 2025-02-08 17:26:02.878419

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "65fd8c044e17"
down_revision = "4a304862e77d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
