"""init

Revision ID: 667b016136dd
Revises: bb2906fa5837
Create Date: 2025-10-13 18:52:58.840967

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "667b016136dd"
down_revision = "bb2906fa5837"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
