"""init

Revision ID: 66b1dd689061
Revises: c00059e74d77
Create Date: 2024-10-10 19:15:49.874508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b1dd689061'
down_revision = 'c00059e74d77'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
