"""init

Revision ID: 67d95e9819ae
Revises: 22c139bcfcd6
Create Date: 2025-02-04 15:13:53.440180

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '67d95e9819ae'
down_revision = '22c139bcfcd6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
