"""init

Revision ID: 67f51ac9fb83
Revises: 037e1333eecb
Create Date: 2025-11-25 19:25:03.094080

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '67f51ac9fb83'
down_revision = '037e1333eecb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
