"""init

Revision ID: 67f6a6425219
Revises: c89b859eda8f
Create Date: 2024-10-16 10:41:14.607435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f6a6425219'
down_revision = 'c89b859eda8f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
