"""init

Revision ID: 68298c9ac5d6
Revises: 8df05dd4100f
Create Date: 2025-02-01 23:21:59.969309

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "68298c9ac5d6"
down_revision = "8df05dd4100f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
