"""init

Revision ID: 6857fcd812b4
Revises: 2af9d83171c3
Create Date: 2025-01-10 21:22:48.486720

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "6857fcd812b4"
down_revision = "2af9d83171c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
