"""init

Revision ID: 6888125f30ac
Revises: 433cfe1cb060
Create Date: 2025-01-08 23:00:48.316757

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "6888125f30ac"
down_revision = "433cfe1cb060"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
