"""init

Revision ID: 68bb0d1a9e59
Revises: a828a568135a
Create Date: 2024-10-15 23:26:28.859328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bb0d1a9e59'
down_revision = 'a828a568135a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
