"""init

Revision ID: 68e85d4fba2c
Revises: aba71c40f6f6
Create Date: 2025-02-10 22:45:13.124438

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '68e85d4fba2c'
down_revision = 'aba71c40f6f6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
