"""init

Revision ID: 6926c4abc08f
Revises: ae11355b5fee
Create Date: 2024-10-15 22:11:37.657529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6926c4abc08f'
down_revision = 'ae11355b5fee'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
