"""init

Revision ID: 69a6380ec5ed
Revises: 04fac5c0795a
Create Date: 2025-02-04 00:50:22.782044

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "69a6380ec5ed"
down_revision = "04fac5c0795a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
