"""init

Revision ID: 6a1768538ff8
Revises: a36a7eb0352d
Create Date: 2025-01-13 12:52:42.119124

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6a1768538ff8'
down_revision = 'a36a7eb0352d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
