"""init

Revision ID: 6a2b39280e87
Revises: f2167c6382c8
Create Date: 2025-01-23 22:26:51.105133

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6a2b39280e87'
down_revision = 'f2167c6382c8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
