"""init

Revision ID: 6b1323932989
Revises: 8696e978c295
Create Date: 2025-01-14 23:09:12.433523

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6b1323932989'
down_revision = '8696e978c295'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
