"""init

Revision ID: 6b6676c263fe
Revises: 123f38ad5576
Create Date: 2025-02-18 14:01:39.501991

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6b6676c263fe'
down_revision = '123f38ad5576'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
