"""init

Revision ID: 6ba98c3d1c76
Revises: 548f7ce2a2e7
Create Date: 2024-09-13 20:10:07.008549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba98c3d1c76'
down_revision = '548f7ce2a2e7'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
