"""init

Revision ID: 6bdcdd53b675
Revises: 649ee559359f
Create Date: 2024-09-13 22:04:02.933616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdcdd53b675'
down_revision = '649ee559359f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
