"""init

Revision ID: 6bff9d2aea65
Revises: a81df720669b
Create Date: 2025-01-24 21:25:04.398504

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6bff9d2aea65'
down_revision = 'a81df720669b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
