"""init

Revision ID: 6c120d5b4057
Revises: 0fdd1ba79e9c
Create Date: 2024-09-13 22:11:52.246431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c120d5b4057'
down_revision = '0fdd1ba79e9c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
