"""init

Revision ID: 6cb953e35a25
Revises: 35d18bf524e1
Create Date: 2025-02-08 17:56:11.150858

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "6cb953e35a25"
down_revision = "35d18bf524e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
