"""init

Revision ID: 6cf20eec9303
Revises: 1143772838ed
Create Date: 2025-11-25 17:57:00.353664

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6cf20eec9303'
down_revision = '1143772838ed'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
