"""init

Revision ID: 6e2feaa8120f
Revises: d273c567d270
Create Date: 2025-01-25 04:16:05.281944

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "6e2feaa8120f"
down_revision = "d273c567d270"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
