"""init

Revision ID: 6f4da2d5df2a
Revises: 2209e3ef653c
Create Date: 2025-01-23 03:22:05.857451

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "6f4da2d5df2a"
down_revision = "2209e3ef653c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
