"""init

Revision ID: 6fede69cc080
Revises: 0962df5794a1
Create Date: 2025-02-10 09:47:54.261997

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6fede69cc080'
down_revision = '0962df5794a1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
