"""init

Revision ID: 6ff8a80ae727
Revises: 83bb94a788df
Create Date: 2025-01-26 16:26:56.952468

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '6ff8a80ae727'
down_revision = '83bb94a788df'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
