"""init

Revision ID: 70b585e9a0b7
Revises: 28c8a2b241eb
Create Date: 2025-01-23 23:53:00.002540

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "70b585e9a0b7"
down_revision = "28c8a2b241eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
