"""init

Revision ID: 71d1f3dcbf57
Revises: 57396a5dcacf
Create Date: 2024-12-09 22:42:37.546224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d1f3dcbf57'
down_revision = '57396a5dcacf'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
