"""init

Revision ID: 72a368ede567
Revises: 3a546e215519
Create Date: 2024-08-29 11:43:30.340849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a368ede567'
down_revision = '3a546e215519'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
