"""init

Revision ID: 7316dac1badb
Revises: 5b72d1df9264
Create Date: 2025-02-10 17:02:38.178990

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7316dac1badb"
down_revision = "5b72d1df9264"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
