"""init

Revision ID: 735ecb17bb99
Revises: 4c9cb7a9e77a
Create Date: 2025-02-01 22:07:25.055365

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "735ecb17bb99"
down_revision = "4c9cb7a9e77a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
