"""init

Revision ID: 738a3b9725fb
Revises: 7a889a7602cb
Create Date: 2025-02-10 16:10:19.605566

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '738a3b9725fb'
down_revision = '7a889a7602cb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
