"""init

Revision ID: 74462cdfa742
Revises: c71410fb48f0
Create Date: 2025-02-10 15:37:34.177057

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "74462cdfa742"
down_revision = "c71410fb48f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
