"""init

Revision ID: 74a505b43e82
Revises: a06c22072052
Create Date: 2025-01-31 20:52:26.151785

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '74a505b43e82'
down_revision = 'a06c22072052'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
