"""init

Revision ID: 74e0be5f2265
Revises: 8fba63d0f14a
Create Date: 2024-09-13 15:58:28.561749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e0be5f2265'
down_revision = '8fba63d0f14a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
