"""init

Revision ID: 7536d71d2f7b
Revises: f6e72c76f3e4
Create Date: 2025-02-10 15:25:54.210980

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7536d71d2f7b"
down_revision = "f6e72c76f3e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
