"""init

Revision ID: 761d8d0abf6e
Revises: 018a68befaaa
Create Date: 2025-01-13 13:44:25.972173

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "761d8d0abf6e"
down_revision = "018a68befaaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
