"""init

Revision ID: 76fd9da56db2
Revises: a936d2c23fb9
Create Date: 2025-01-10 13:08:57.744570

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "76fd9da56db2"
down_revision = "a936d2c23fb9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
