"""init

Revision ID: 774d67dcf590
Revises: 7316dac1badb
Create Date: 2025-02-10 17:04:43.298542

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "774d67dcf590"
down_revision = "7316dac1badb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
