"""init

Revision ID: 7825d477b771
Revises: 89788d841c8a
Create Date: 2025-11-25 18:47:19.098896

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7825d477b771'
down_revision = '89788d841c8a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
