"""init

Revision ID: 782c22483c37
Revises: 488afbd92edc
Create Date: 2024-09-12 22:59:47.824914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782c22483c37'
down_revision = '488afbd92edc'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
