"""init

Revision ID: 78b374dffb56
Revises: b940dfde7472
Create Date: 2025-01-20 13:28:58.679200

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '78b374dffb56'
down_revision = 'b940dfde7472'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
