"""init

Revision ID: 78cd9be1043d
Revises: 830f726c8423
Create Date: 2024-09-13 18:57:37.876975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cd9be1043d'
down_revision = '830f726c8423'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
