"""init

Revision ID: 79448ac31888
Revises: 3467f84fad07
Create Date: 2025-01-25 00:53:12.830922

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "79448ac31888"
down_revision = "3467f84fad07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
