"""init

Revision ID: 797b3edf4c87
Revises: 8b40b9fbfca4
Create Date: 2025-01-24 16:40:03.258706

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '797b3edf4c87'
down_revision = '8b40b9fbfca4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
