"""init

Revision ID: 79ac9d5d0520
Revises: 8e388f926f9d
Create Date: 2025-02-03 22:25:33.581672

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '79ac9d5d0520'
down_revision = '8e388f926f9d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
