"""init

Revision ID: 79c1b66330bb
Revises: 6e7a90ab41f4
Create Date: 2025-01-10 16:10:03.662889

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '79c1b66330bb'
down_revision = '6e7a90ab41f4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
