"""init

Revision ID: 7a04bb627b6c
Revises: 071e8234739a
Create Date: 2024-09-12 23:25:45.883066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a04bb627b6c'
down_revision = '071e8234739a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
