"""init

Revision ID: 7a5a548bfc37
Revises: cc401e9283e0
Create Date: 2025-01-09 23:22:10.775663

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7a5a548bfc37'
down_revision = 'cc401e9283e0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
