"""init

Revision ID: 7a5f80506730
Revises: 2dd71562d7cb
Create Date: 2025-01-24 12:32:27.463115

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7a5f80506730"
down_revision = "2dd71562d7cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
