"""init

Revision ID: 7a889a7602cb
Revises: f1220cf21bab
Create Date: 2025-02-10 16:06:08.234515

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7a889a7602cb"
down_revision = "f1220cf21bab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
