"""init

Revision ID: 7b73bf80b31e
Revises: c5b400dc8163
Create Date: 2025-01-09 23:31:52.961211

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7b73bf80b31e'
down_revision = 'c5b400dc8163'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
