"""init

Revision ID: 7b784582d4c5
Revises: a3e47e0dad5a
Create Date: 2025-01-10 11:20:20.609745

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7b784582d4c5"
down_revision = "a3e47e0dad5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
