"""init

Revision ID: 7c1dc5f82bcc
Revises: 91c0719858c0
Create Date: 2025-01-08 23:44:27.847953

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7c1dc5f82bcc"
down_revision = "91c0719858c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
