"""init

Revision ID: 7cf8a72a1d28
Revises: 4c4f728cfdc9
Create Date: 2025-02-10 15:44:20.363277

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7cf8a72a1d28'
down_revision = '4c4f728cfdc9'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
