"""init

Revision ID: 7d6dbd45a76b
Revises: a902ab0dfb14
Create Date: 2025-01-25 04:30:37.620575

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7d6dbd45a76b'
down_revision = 'a902ab0dfb14'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
