"""init

Revision ID: 7dae048d0449
Revises: 3686ba4341b4
Create Date: 2025-11-25 20:25:02.672372

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7dae048d0449'
down_revision = '3686ba4341b4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
