"""init

Revision ID: 7e2fcc604589
Revises: 8ad62098379f
Create Date: 2024-09-13 20:52:51.855736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2fcc604589'
down_revision = '8ad62098379f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
