"""init

Revision ID: 7e613f7e5189
Revises: e88552d592c1
Create Date: 2025-01-31 00:09:52.323821

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7e613f7e5189'
down_revision = 'e88552d592c1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
