"""init

Revision ID: 7e85052bacfd
Revises: 1cc963ff68c3
Create Date: 2025-01-23 23:20:26.708524

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7e85052bacfd'
down_revision = '1cc963ff68c3'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
