"""init

Revision ID: 7e8fc2a899f5
Revises: f2fb5eb7dc30
Create Date: 2025-01-09 13:38:28.597027

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7e8fc2a899f5'
down_revision = 'f2fb5eb7dc30'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
