"""init

Revision ID: 7e9e35ebd8c6
Revises: 423678edbcf0
Create Date: 2025-02-02 14:32:27.307610

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7e9e35ebd8c6"
down_revision = "423678edbcf0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
