"""init

Revision ID: 7ed0549ba3ae
Revises: 1d5839bfd3d4
Create Date: 2025-01-10 11:27:40.740796

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "7ed0549ba3ae"
down_revision = "1d5839bfd3d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
