"""init

Revision ID: 7ef4d3d3ef09
Revises: 3ff409b0b020
Create Date: 2025-01-24 03:35:00.425933

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7ef4d3d3ef09'
down_revision = '3ff409b0b020'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
