"""init

Revision ID: 81583f0897ce
Revises: 21bd967b7159
Create Date: 2025-01-24 13:10:58.642985

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "81583f0897ce"
down_revision = "21bd967b7159"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
