"""init

Revision ID: 8172c103d3bf
Revises: 6ff8a80ae727
Create Date: 2025-01-26 17:34:44.698958

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "8172c103d3bf"
down_revision = "6ff8a80ae727"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
