"""init

Revision ID: 817c0110ed5c
Revises: 71d1f3dcbf57
Create Date: 2024-12-09 23:02:13.318246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817c0110ed5c'
down_revision = '71d1f3dcbf57'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
