"""init

Revision ID: 820161beb95f
Revises: c998e23b59da
Create Date: 2025-01-09 18:04:27.208745

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '820161beb95f'
down_revision = 'c998e23b59da'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
