"""init

Revision ID: 82097cd64242
Revises: d8ab81a66b6f
Create Date: 2024-09-13 21:37:54.903820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82097cd64242'
down_revision = 'd8ab81a66b6f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
