"""init

Revision ID: 828e2d8fec52
Revises: cd6820a7c91f
Create Date: 2025-02-04 17:18:47.107626

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "828e2d8fec52"
down_revision = "cd6820a7c91f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
