"""init

Revision ID: 830f726c8423
Revises: 1c6bb20114ab
Create Date: 2024-09-13 17:14:26.428931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830f726c8423'
down_revision = '1c6bb20114ab'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
