"""init

Revision ID: 83bb94a788df
Revises: 19a6f0340152
Create Date: 2025-01-26 16:25:18.314363

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '83bb94a788df'
down_revision = '19a6f0340152'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
