"""init

Revision ID: 85c48d2dbda4
Revises: 040c02cb7745
Create Date: 2025-02-18 14:31:26.199874

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '85c48d2dbda4'
down_revision = '040c02cb7745'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
