"""init

Revision ID: 8696e978c295
Revises: 231a58cb157b
Create Date: 2025-01-14 19:17:16.080279

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "8696e978c295"
down_revision = "231a58cb157b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
