"""init

Revision ID: 87536d455c5a
Revises: db9cc88b0abb
Create Date: 2025-01-09 10:57:03.560803

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '87536d455c5a'
down_revision = 'db9cc88b0abb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
