"""init

Revision ID: 88b82b3a38de
Revises: d126a1e82cf3
Create Date: 2025-01-09 10:46:52.106561

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "88b82b3a38de"
down_revision = "d126a1e82cf3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
