"""init

Revision ID: 89488db2aa59
Revises: 42909b25e6c2
Create Date: 2025-01-12 14:04:16.566566

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "89488db2aa59"
down_revision = "42909b25e6c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
