"""init

Revision ID: 89788d841c8a
Revises: ed2b1ac715bb
Create Date: 2025-11-25 18:37:08.189244

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '89788d841c8a'
down_revision = 'ed2b1ac715bb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
