"""init

Revision ID: 8ad62098379f
Revises: b51069a44456
Create Date: 2024-09-13 20:46:35.396782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad62098379f'
down_revision = 'b51069a44456'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
