"""init

Revision ID: 8b40b9fbfca4
Revises: eb8d754593c5
Create Date: 2025-01-24 16:38:37.778240

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8b40b9fbfca4'
down_revision = 'eb8d754593c5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
