"""init

Revision ID: 8b8690a0c7ab
Revises: 735ecb17bb99
Create Date: 2025-02-01 22:10:40.065033

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "8b8690a0c7ab"
down_revision = "735ecb17bb99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
