"""init

Revision ID: 8bb87cbc2f04
Revises: 774d67dcf590
Create Date: 2025-02-10 17:50:08.155471

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "8bb87cbc2f04"
down_revision = "774d67dcf590"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
