"""init

Revision ID: 8bc95bf5f66b
Revises: fffcbb0f69c5
Create Date: 2024-09-13 21:20:45.825578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc95bf5f66b'
down_revision = 'fffcbb0f69c5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
