"""init

Revision ID: 8c62f2186d79
Revises: bccb1ca19f4b
Create Date: 2024-08-28 13:08:40.163162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c62f2186d79'
down_revision = 'bccb1ca19f4b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
