"""init

Revision ID: 8ca7cd7efe29
Revises: 948b30729fa2
Create Date: 2024-09-11 01:09:14.209547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca7cd7efe29'
down_revision = '948b30729fa2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
