"""init

Revision ID: 8cb12bf4036e
Revises: ad69b31bdd8e
Create Date: 2024-10-29 15:30:11.800016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb12bf4036e'
down_revision = 'ad69b31bdd8e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
