"""init

Revision ID: 8dd0367added
Revises: 0801f5ceef44
Create Date: 2025-01-09 00:05:49.397358

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "8dd0367added"
down_revision = "0801f5ceef44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
