"""init

Revision ID: 8dd887a39b71
Revises: 975d1fe234b3
Create Date: 2025-02-15 17:07:14.826674

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "8dd887a39b71"
down_revision = "975d1fe234b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
