"""init

Revision ID: 8ddd9764843b
Revises: bda7592920d6
Create Date: 2025-01-09 02:13:33.057228

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8ddd9764843b'
down_revision = 'bda7592920d6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
