"""init

Revision ID: 8df05dd4100f
Revises: 49e0eb13f4a1
Create Date: 2025-02-01 23:16:06.739843

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8df05dd4100f'
down_revision = '49e0eb13f4a1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
