"""init

Revision ID: 8e388f926f9d
Revises: eb231cf49a64
Create Date: 2025-02-03 22:23:48.785992

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "8e388f926f9d"
down_revision = "eb231cf49a64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
