"""init

Revision ID: 8f740b3d68d9
Revises: 67d95e9819ae
Create Date: 2025-02-04 15:58:18.105932

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "8f740b3d68d9"
down_revision = "67d95e9819ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
