"""init

Revision ID: 8fa2690b6db3
Revises: d49d861a6b1d
Create Date: 2025-01-23 03:51:35.659977

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8fa2690b6db3'
down_revision = 'd49d861a6b1d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
