"""init

Revision ID: 8fba63d0f14a
Revises: 2c1e6916454a
Create Date: 2024-09-12 23:40:30.816740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fba63d0f14a'
down_revision = '2c1e6916454a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
