"""init

Revision ID: 90212d4b5912
Revises: 7286facfe997
Create Date: 2025-01-24 03:11:53.913098

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "90212d4b5912"
down_revision = "7286facfe997"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
