"""init

Revision ID: 9057ed79991b
Revises: 475a6a9b1412
Create Date: 2025-01-20 15:37:52.155602

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "9057ed79991b"
down_revision = "475a6a9b1412"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
