"""init

Revision ID: 909afcad5041
Revises: d57bf6418444
Create Date: 2024-10-16 10:28:09.833333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909afcad5041'
down_revision = 'd57bf6418444'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
