"""init

Revision ID: 91c0719858c0
Revises: e42933f4af07
Create Date: 2025-01-08 23:30:47.121635

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '91c0719858c0'
down_revision = 'e42933f4af07'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
