"""init

Revision ID: 92406f42956d
Revises: 4a96b0c91759
Create Date: 2025-02-04 01:08:57.517060

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "92406f42956d"
down_revision = "4a96b0c91759"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
