"""init

Revision ID: 93393d7ad942
Revises: 02539df60117
Create Date: 2025-10-23 19:11:24.603606

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "93393d7ad942"
down_revision = "02539df60117"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
