"""init

Revision ID: 9394495c154e
Revises: 0fb4389a682a
Create Date: 2025-01-24 01:22:29.913691

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "9394495c154e"
down_revision = "0fb4389a682a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
