"""init

Revision ID: 93f152e5bfa4
Revises: f77d747174c3
Create Date: 2025-10-22 22:07:25.707838

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "93f152e5bfa4"
down_revision = "f77d747174c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
