"""init

Revision ID: 948b30729fa2
Revises: 08f0b1f4b229
Create Date: 2024-09-11 01:06:57.427429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948b30729fa2'
down_revision = '08f0b1f4b229'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
