"""init

Revision ID: 95c67b3d97e7
Revises: 997676ec09a0
Create Date: 2025-01-24 01:47:43.454780

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '95c67b3d97e7'
down_revision = '997676ec09a0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
