"""init

Revision ID: 96b93a3809f2
Revises: eafcdbc4b3c6
Create Date: 2025-01-25 01:10:48.040186

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "96b93a3809f2"
down_revision = "eafcdbc4b3c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
