"""init

Revision ID: 96d45e6072a3
Revises: cd1eb961aa2b
Create Date: 2025-02-18 14:06:26.342063

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "96d45e6072a3"
down_revision = "cd1eb961aa2b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
