"""init

Revision ID: 970c7e6280cb
Revises: b0f934017da9
Create Date: 2024-09-13 16:44:56.937363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970c7e6280cb'
down_revision = 'b0f934017da9'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
