"""init

Revision ID: 975d1fe234b3
Revises: 1a32382a6b6b
Create Date: 2025-02-13 11:51:29.409458

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "975d1fe234b3"
down_revision = "1a32382a6b6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
