"""init

Revision ID: 997676ec09a0
Revises: c7bacfcc7a47
Create Date: 2025-01-24 01:43:09.004410

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "997676ec09a0"
down_revision = "c7bacfcc7a47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
