"""init

Revision ID: 9a398dbfb0c5
Revises: 7c1dc5f82bcc
Create Date: 2025-01-08 23:50:59.526189

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9a398dbfb0c5'
down_revision = '7c1dc5f82bcc'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
