"""init

Revision ID: 9b0d523f4784
Revises: 9c01761e4ce1
Create Date: 2025-01-24 16:31:02.676757

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9b0d523f4784'
down_revision = '9c01761e4ce1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
