"""init

Revision ID: 9b3426fb8d83
Revises: 51861868a959
Create Date: 2025-10-13 17:38:20.324116

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "9b3426fb8d83"
down_revision = "51861868a959"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
