"""init

Revision ID: 9b95a114e99a
Revises: 640a9f6e941d
Create Date: 2025-01-31 20:34:35.239022

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9b95a114e99a'
down_revision = '640a9f6e941d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
