"""init

Revision ID: 9be6c9bea20e
Revises: a2af69320bc3
Create Date: 2025-01-09 01:28:30.555470

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "9be6c9bea20e"
down_revision = "a2af69320bc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
