"""init

Revision ID: 9bf761e86e79
Revises: 1bd2ceafdcdf
Create Date: 2025-02-01 22:54:31.945511

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9bf761e86e79'
down_revision = '1bd2ceafdcdf'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
