"""init

Revision ID: 9c01761e4ce1
Revises: 3c251bea7dba
Create Date: 2025-01-24 16:24:28.685647

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9c01761e4ce1'
down_revision = '3c251bea7dba'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_product_category', ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_product_category', type_='unique')
    # ### end Alembic commands ###
