"""init

Revision ID: 9c8e7ca9d79e
Revises: 6cf20eec9303
Create Date: 2025-11-25 18:08:11.638240

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9c8e7ca9d79e'
down_revision = '6cf20eec9303'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
