"""init

Revision ID: 9c8f1b6e2ea5
Revises: 820161beb95f
Create Date: 2025-01-09 18:54:26.112952

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "9c8f1b6e2ea5"
down_revision = "820161beb95f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
