"""init

Revision ID: 9d052b57c519
Revises: e4efe45c27b8
Create Date: 2025-01-23 23:42:21.618651

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9d052b57c519'
down_revision = 'e4efe45c27b8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
