"""init

Revision ID: 9d09d4a3dad9
Revises: 25ca250237bc
Create Date: 2025-02-08 17:30:23.474688

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "9d09d4a3dad9"
down_revision = "25ca250237bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
