"""init

Revision ID: 9d6ab8891731
Revises: 2b9de53e1877
Create Date: 2025-02-04 17:11:31.793262

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9d6ab8891731'
down_revision = '2b9de53e1877'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
