"""init

Revision ID: 9d7a77d31571
Revises: bb8afa07170c
Create Date: 2025-01-12 03:28:38.340179

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9d7a77d31571'
down_revision = 'bb8afa07170c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
