"""init

Revision ID: 9de5fbaf0080
Revises: cba36b6a5e85
Create Date: 2025-01-09 23:15:37.271441

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9de5fbaf0080'
down_revision = 'cba36b6a5e85'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
