"""init

Revision ID: 9e0bd2fb80bd
Revises: 0cb676c3219a
Create Date: 2025-01-25 03:50:28.435816

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "9e0bd2fb80bd"
down_revision = "0cb676c3219a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
