"""init

Revision ID: 9e2e0b714205
Revises: f45899ab5689
Create Date: 2025-02-18 13:54:20.954153

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9e2e0b714205'
down_revision = 'f45899ab5689'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
