"""init

Revision ID: 9ebfec5748db
Revises: f981fae8e5b8
Create Date: 2024-08-30 15:08:13.092116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebfec5748db'
down_revision = 'f981fae8e5b8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
