"""init

Revision ID: 9efb8229c35c
Revises: 1a8d63cc4a4d
Create Date: 2024-10-29 15:52:49.083851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efb8229c35c'
down_revision = '1a8d63cc4a4d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
