"""init

Revision ID: 9f5b67180d17
Revises: d4c45344edca
Create Date: 2025-11-25 20:43:23.590145

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9f5b67180d17'
down_revision = 'd4c45344edca'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
