"""init

Revision ID: 9fbfa0242495
Revises: 073227655a81
Create Date: 2025-10-03 10:57:26.818208

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9fbfa0242495'
down_revision = '073227655a81'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
