"""init

Revision ID: 9ff0b5f3efa7
Revises: b7e115b832cf
Create Date: 2025-01-25 01:31:31.048525

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = '9ff0b5f3efa7'
down_revision = 'b7e115b832cf'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
