"""init

Revision ID: a091f5da8a69
Revises: b4b66635da5f
Create Date: 2025-11-25 20:55:36.926209

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a091f5da8a69'
down_revision = 'b4b66635da5f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
