"""init

Revision ID: a14d45979beb
Revises: cf723ae8a961
Create Date: 2025-01-24 22:30:45.067720

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a14d45979beb"
down_revision = "cf723ae8a961"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
