"""init

Revision ID: a2a638d9b71b
Revises: d4b00110fb04
Create Date: 2025-01-20 15:22:48.976126

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a2a638d9b71b'
down_revision = 'd4b00110fb04'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
