"""init

Revision ID: a2af69320bc3
Revises: 1fa1c58aaefd
Create Date: 2025-01-09 00:41:18.077836

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a2af69320bc3'
down_revision = '1fa1c58aaefd'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
