"""init

Revision ID: a36a7eb0352d
Revises: 30b71eeb90be
Create Date: 2025-01-13 12:50:02.490276

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a36a7eb0352d"
down_revision = "30b71eeb90be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
