"""init

Revision ID: a3cc5e4444b4
Revises: 5e83c506d8d1
Create Date: 2025-01-11 03:43:19.236445

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a3cc5e4444b4"
down_revision = "5e83c506d8d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
