"""init

Revision ID: a3e47e0dad5a
Revises: 05ba6d94a691
Create Date: 2025-01-10 11:13:48.409676

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a3e47e0dad5a'
down_revision = '05ba6d94a691'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
