"""init

Revision ID: a4157a92cea8
Revises: 439be8eeee1e
Create Date: 2025-01-12 03:11:53.478865

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a4157a92cea8"
down_revision = "439be8eeee1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
