"""init

Revision ID: a42021f0ca06
Revises: 42a413acf375
Create Date: 2025-01-24 03:17:33.469716

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a42021f0ca06"
down_revision = "42a413acf375"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
