"""init

Revision ID: a4590f651b78
Revises: bc57e52c4814
Create Date: 2025-11-25 17:25:58.541323

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a4590f651b78'
down_revision = 'bc57e52c4814'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
