"""init

Revision ID: a552303de69a
Revises: 7536d71d2f7b
Create Date: 2025-02-10 15:26:25.334702

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a552303de69a"
down_revision = "7536d71d2f7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
