"""init

Revision ID: a5c4f4b8b5bf
Revises: edd0479f11cf
Create Date: 2025-01-12 02:12:54.769473

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a5c4f4b8b5bf'
down_revision = 'edd0479f11cf'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
