"""init

Revision ID: a5f42aa3e2ec
Revises: 3b421e05559c
Create Date: 2025-01-10 20:28:36.963738

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a5f42aa3e2ec"
down_revision = "3b421e05559c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
