"""init

Revision ID: a652afbbb19a
Revises: 5776738367ae
Create Date: 2024-09-12 21:50:21.207981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a652afbbb19a'
down_revision = '5776738367ae'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
