"""init

Revision ID: a67672dd9a35
Revises: e21ba14319a6
Create Date: 2025-01-09 16:02:49.154444

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a67672dd9a35"
down_revision = "e21ba14319a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
