"""init

Revision ID: a6c6154bc032
Revises: 81583f0897ce
Create Date: 2025-01-24 13:17:07.008150

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a6c6154bc032"
down_revision = "81583f0897ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
