"""init

Revision ID: a75f424d34fd
Revises: 96d45e6072a3
Create Date: 2025-02-18 14:12:53.893099

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a75f424d34fd"
down_revision = "96d45e6072a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
