"""init

Revision ID: a81df720669b
Revises: 18fdbc7f6d7a
Create Date: 2025-01-24 17:28:01.477803

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a81df720669b'
down_revision = '18fdbc7f6d7a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
