"""init

Revision ID: a821ea323b4d
Revises: ef182f74c97c
Create Date: 2025-02-19 00:13:02.893175

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a821ea323b4d'
down_revision = 'ef182f74c97c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
