"""init

Revision ID: a868408566df
Revises: 193fdf3c18f5
Create Date: 2024-09-13 21:06:43.113674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a868408566df'
down_revision = '193fdf3c18f5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
