"""init

Revision ID: a902ab0dfb14
Revises: 6e2feaa8120f
Create Date: 2025-01-25 04:25:39.073387

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a902ab0dfb14'
down_revision = '6e2feaa8120f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
