"""init

Revision ID: a936d2c23fb9
Revises: 85a4596a543c
Create Date: 2025-01-10 12:59:54.881984

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a936d2c23fb9"
down_revision = "85a4596a543c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
