"""init

Revision ID: a95721b9c68a
Revises: f9f4414f5f6e
Create Date: 2024-08-27 18:00:29.243493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95721b9c68a'
down_revision = 'f9f4414f5f6e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
