"""init

Revision ID: a9725fd03f65
Revises: 797b3edf4c87
Create Date: 2025-01-24 16:41:15.645706

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "a9725fd03f65"
down_revision = "797b3edf4c87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
