"""init

Revision ID: aa2af13e5566
Revises: 0857cb172899
Create Date: 2025-02-03 21:32:35.786217

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "aa2af13e5566"
down_revision = "0857cb172899"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
