"""init

Revision ID: aaa203953a48
Revises: 9c8f1b6e2ea5
Create Date: 2025-01-09 22:14:03.993036

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'aaa203953a48'
down_revision = '9c8f1b6e2ea5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
