"""init

Revision ID: aae4d24163d0
Revises: 3a398aa40954
Create Date: 2025-01-23 03:19:02.489647

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "aae4d24163d0"
down_revision = "3a398aa40954"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
