"""init

Revision ID: ab3258396bd5
Revises: b8f261853307
Create Date: 2025-01-24 03:56:39.386058

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "ab3258396bd5"
down_revision = "b8f261853307"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
