"""init

Revision ID: aba71c40f6f6
Revises: 0dd34f696263
Create Date: 2025-02-10 22:33:31.561128

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "aba71c40f6f6"
down_revision = "0dd34f696263"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
