"""init

Revision ID: ac6585a1ed97
Revises: 343a4f14fbbd
Create Date: 2024-09-12 22:48:48.974015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6585a1ed97'
down_revision = '343a4f14fbbd'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
