"""init

Revision ID: aca84ab94b27
Revises: 5a2e8ede4785
Create Date: 2025-01-12 03:40:54.688182

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "aca84ab94b27"
down_revision = "5a2e8ede4785"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
