"""init

Revision ID: ad69b31bdd8e
Revises: 3bb5fc0bee33
Create Date: 2024-10-29 15:24:25.031133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad69b31bdd8e'
down_revision = '3bb5fc0bee33'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
