"""init

Revision ID: ae11355b5fee
Revises: 03b8fd815839
Create Date: 2024-10-15 21:20:21.962296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae11355b5fee'
down_revision = '03b8fd815839'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
