"""init

Revision ID: ae865023c486
Revises: f661c43fff6e
Create Date: 2025-02-03 22:11:49.204661

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ae865023c486'
down_revision = 'f661c43fff6e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
