"""init

Revision ID: af5809ed5b96
Revises: e2a821f38c15
Create Date: 2025-01-20 16:01:45.640651

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'af5809ed5b96'
down_revision = 'e2a821f38c15'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
