"""init

Revision ID: b0e51725c398
Revises: 8172c103d3bf
Create Date: 2025-01-26 17:37:40.177530

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b0e51725c398'
down_revision = '8172c103d3bf'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
