"""init

Revision ID: b0f934017da9
Revises: 74e0be5f2265
Create Date: 2024-09-13 16:42:42.024563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f934017da9'
down_revision = '74e0be5f2265'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
