"""init

Revision ID: b1394ba55460
Revises: d6e27de69e13
Create Date: 2025-01-24 01:01:33.515672

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b1394ba55460'
down_revision = 'd6e27de69e13'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
