"""init

Revision ID: b173c0afa615
Revises: 87536d455c5a
Create Date: 2025-01-09 10:58:14.431446

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b173c0afa615'
down_revision = '87536d455c5a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
