"""init

Revision ID: b20cbe0bf7d1
Revises: c4914dc9a47c
Create Date: 2025-01-10 15:50:56.192538

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b20cbe0bf7d1'
down_revision = 'c4914dc9a47c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('fiscal_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'fiscal_id')
    # ### end Alembic commands ###
