"""init

Revision ID: b213d9f45226
Revises: dacfdf1ebf72
Create Date: 2025-02-03 23:01:51.113470

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b213d9f45226'
down_revision = 'dacfdf1ebf72'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'mail_verified')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mail_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
