"""init

Revision ID: b28c90526e12
Revises: b9986b7fc695
Create Date: 2025-02-02 01:22:18.048767

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b28c90526e12"
down_revision = "b9986b7fc695"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
