"""init

Revision ID: b2ba0760a640
Revises: ceda782dd3c6
Create Date: 2024-09-11 00:41:52.393117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ba0760a640'
down_revision = 'ceda782dd3c6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
