"""init

Revision ID: b4b66635da5f
Revises: 3c2f1b4a827b
Create Date: 2025-11-25 20:53:49.036919

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b4b66635da5f'
down_revision = '3c2f1b4a827b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
