"""init

Revision ID: b50101664db0
Revises: 42a492e4849c
Create Date: 2025-01-10 13:13:54.461710

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b50101664db0'
down_revision = '42a492e4849c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
