"""init

Revision ID: b51069a44456
Revises: bf0705b293e0
Create Date: 2024-09-13 20:19:44.716818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51069a44456'
down_revision = 'bf0705b293e0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
