"""init

Revision ID: b571c3a93f08
Revises: c61bfee190ee
Create Date: 2024-08-30 15:48:26.583525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b571c3a93f08'
down_revision = 'c61bfee190ee'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
