"""init

Revision ID: b5e29000373b
Revises: 1f3b9211f66c
Create Date: 2025-01-23 23:28:28.441231

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b5e29000373b"
down_revision = "1f3b9211f66c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
