"""init

Revision ID: b6dd43cd6b09
Revises: fa9c69993c78
Create Date: 2025-01-11 03:33:21.657502

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b6dd43cd6b09"
down_revision = "fa9c69993c78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
