"""init

Revision ID: b7e115b832cf
Revises: e830c0365eae
Create Date: 2025-01-25 01:29:06.551932

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b7e115b832cf"
down_revision = "e830c0365eae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
