"""init

Revision ID: b83f29d82a62
Revises: 218e07d98b86
Create Date: 2025-01-23 03:08:52.414837

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b83f29d82a62'
down_revision = '218e07d98b86'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
