"""init

Revision ID: b85aab293e6a
Revises: d05d780bf056
Create Date: 2025-01-24 23:19:31.083546

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b85aab293e6a"
down_revision = "d05d780bf056"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
