"""init

Revision ID: b8bd894a3c07
Revises: 6926c4abc08f
Create Date: 2024-10-15 22:35:45.645526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8bd894a3c07'
down_revision = '6926c4abc08f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
