"""init

Revision ID: b8d5ad3f7243
Revises: d0bb8002e3cd
Create Date: 2025-01-08 21:14:54.440936

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b8d5ad3f7243'
down_revision = 'd0bb8002e3cd'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bill', ['id'])
    op.create_unique_constraint(None, 'category', ['id'])
    op.drop_column('category', 'test')
    op.create_unique_constraint(None, 'goods', ['id'])
    op.create_unique_constraint(None, 'login_link', ['id'])
    op.create_unique_constraint(None, 'seller', ['id'])
    op.create_unique_constraint(None, 'unit', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'unit', type_='unique')
    op.drop_constraint(None, 'seller', type_='unique')
    op.drop_constraint(None, 'login_link', type_='unique')
    op.drop_constraint(None, 'goods', type_='unique')
    op.add_column('category', sa.Column('test', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_constraint(None, 'bill', type_='unique')
    # ### end Alembic commands ###
