"""init

Revision ID: b8f261853307
Revises: 7ef4d3d3ef09
Create Date: 2025-01-24 03:35:50.302625

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b8f261853307"
down_revision = "7ef4d3d3ef09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
