"""init

Revision ID: b90799f325da
Revises: bf4aa8e97150
Create Date: 2025-01-24 12:10:29.010493

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b90799f325da"
down_revision = "bf4aa8e97150"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
