"""init

Revision ID: b92cc04fa8e0
Revises: b571c3a93f08
Create Date: 2024-09-04 23:54:54.956610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92cc04fa8e0'
down_revision = 'b571c3a93f08'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
