"""init

Revision ID: b9333414c629
Revises: 5f91c7ae89f9
Create Date: 2025-02-07 18:21:31.313618

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b9333414c629"
down_revision = "5f91c7ae89f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
