"""init

Revision ID: b940dfde7472
Revises: f452fdd6b6e7
Create Date: 2025-01-20 13:07:36.937553

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b940dfde7472'
down_revision = 'f452fdd6b6e7'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
