"""init

Revision ID: b9986b7fc695
Revises: eb6b0bcaf6f6
Create Date: 2025-02-02 01:18:13.627949

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'b9986b7fc695'
down_revision = 'eb6b0bcaf6f6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
