"""init

Revision ID: b9a7e306934f
Revises: 1889e96c8fcd
Create Date: 2025-01-09 13:32:07.387049

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "b9a7e306934f"
down_revision = "1889e96c8fcd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
