"""init

Revision ID: bada4a8a93f5
Revises: 34a69335e3de
Create Date: 2025-01-24 01:06:18.282230

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "bada4a8a93f5"
down_revision = "34a69335e3de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
