"""init

Revision ID: bb2906fa5837
Revises: dd2a724a1727
Create Date: 2025-10-13 18:46:11.575557

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bb2906fa5837'
down_revision = 'dd2a724a1727'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
