"""init

Revision ID: bb3c1a020d89
Revises: 9ff0b5f3efa7
Create Date: 2025-01-25 01:32:08.888297

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "bb3c1a020d89"
down_revision = "9ff0b5f3efa7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
