"""init

Revision ID: bb720eec2366
Revises: f3437cec5a02
Create Date: 2025-02-01 21:05:52.396844

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "bb720eec2366"
down_revision = "f3437cec5a02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
