"""init

Revision ID: bb8afa07170c
Revises: a4157a92cea8
Create Date: 2025-01-12 03:17:24.413446

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bb8afa07170c'
down_revision = 'a4157a92cea8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
