"""init

Revision ID: bc0fe551b78f
Revises: 13e0d6f00469
Create Date: 2025-02-18 16:09:24.550247

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "bc0fe551b78f"
down_revision = "13e0d6f00469"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
