"""init

Revision ID: bc402ff58727
Revises: 317f6407c78e
Create Date: 2025-01-23 01:58:17.631818

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "bc402ff58727"
down_revision = "317f6407c78e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
