"""init

Revision ID: bc57e52c4814
Revises: bf7e62c03bc2
Create Date: 2025-11-25 16:50:22.938266

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bc57e52c4814'
down_revision = 'bf7e62c03bc2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
