"""init

Revision ID: bccb1ca19f4b
Revises: e412aceb1c04
Create Date: 2024-08-28 12:26:24.459945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccb1ca19f4b'
down_revision = 'e412aceb1c04'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
