"""init

Revision ID: bda7592920d6
Revises: e5193a9be12f
Create Date: 2025-01-09 02:08:02.130765

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "bda7592920d6"
down_revision = "e5193a9be12f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
