"""init

Revision ID: be27e2b088b5
Revises: 4868861f4fa9
Create Date: 2025-02-02 00:53:40.512286

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'be27e2b088b5'
down_revision = '4868861f4fa9'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
