"""init

Revision ID: be95596c6b5d
Revises: 344e45bdb856
Create Date: 2024-09-13 20:02:06.975993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be95596c6b5d'
down_revision = '344e45bdb856'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
