"""init

Revision ID: bf0304a642e0
Revises: a3cc5e4444b4
Create Date: 2025-01-11 03:51:43.843938

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "bf0304a642e0"
down_revision = "a3cc5e4444b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
