"""init

Revision ID: bf0705b293e0
Revises: 0300f81e2c26
Create Date: 2024-09-13 20:16:10.042279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0705b293e0'
down_revision = '0300f81e2c26'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
