"""init

Revision ID: bf4aa8e97150
Revises: 3cb4161b786c
Create Date: 2025-01-24 12:04:14.982515

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bf4aa8e97150'
down_revision = '3cb4161b786c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
