"""init

Revision ID: bf65d14864a8
Revises: 37a242ef46fa
Create Date: 2025-01-24 03:26:37.287524

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bf65d14864a8'
down_revision = '37a242ef46fa'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
