"""init

Revision ID: bf7e62c03bc2
Revises: 041fe12a717a
Create Date: 2025-11-25 16:48:41.990462

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'bf7e62c03bc2'
down_revision = '041fe12a717a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
