"""init

Revision ID: c00059e74d77
Revises: 5763ba2e4755
Create Date: 2024-10-04 23:35:48.374304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00059e74d77'
down_revision = '5763ba2e4755'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
