"""init

Revision ID: c13ce71aada3
Revises: 7dae048d0449
Create Date: 2025-11-25 20:28:51.274208

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c13ce71aada3'
down_revision = '7dae048d0449'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
