"""init

Revision ID: c14adab1592b
Revises: 544d9f3cc158
Create Date: 2025-01-13 12:38:58.750979

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c14adab1592b"
down_revision = "544d9f3cc158"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
