"""init

Revision ID: c1f8bb738f50
Revises: 7ed0549ba3ae
Create Date: 2025-01-10 11:33:48.728846

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c1f8bb738f50"
down_revision = "7ed0549ba3ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
