"""init

Revision ID: c214429929f2
Revises: dc5eeb55bc74
Create Date: 2025-02-09 18:59:34.107989

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c214429929f2'
down_revision = 'dc5eeb55bc74'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
