"""init

Revision ID: c24a690f43ff
Revises: 392d4be28c89
Create Date: 2025-02-03 23:31:43.370606

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c24a690f43ff'
down_revision = '392d4be28c89'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
