"""init

Revision ID: c24ec49e4cba
Revises: 477108f4f6ed
Create Date: 2025-02-04 16:09:00.449308

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c24ec49e4cba'
down_revision = '477108f4f6ed'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
