"""init

Revision ID: c26eb3dcc0db
Revises: 0da04b3f55db
Create Date: 2025-01-23 22:59:53.067515

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c26eb3dcc0db"
down_revision = "0da04b3f55db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
