"""init

Revision ID: c2821f85be48
Revises: 28661d8a01a8
Create Date: 2025-01-09 13:17:02.930447

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c2821f85be48'
down_revision = '28661d8a01a8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
