"""init

Revision ID: c3199fec875f
Revises: 47c1ff3b9c56
Create Date: 2025-02-01 23:52:28.956576

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c3199fec875f"
down_revision = "47c1ff3b9c56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
