"""init

Revision ID: c3adcea50658
Revises: c8a957811db8
Create Date: 2025-01-10 01:37:38.833380

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c3adcea50658'
down_revision = 'c8a957811db8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
