"""init

Revision ID: c3ce9c4a1058
Revises: fd2cc60defae
Create Date: 2025-01-12 00:07:59.657650

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c3ce9c4a1058'
down_revision = 'fd2cc60defae'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
