"""init

Revision ID: c4ccf814e553
Revises: f46f6c2bbe03
Create Date: 2025-02-10 18:10:23.372584

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c4ccf814e553'
down_revision = 'f46f6c2bbe03'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
