"""init

Revision ID: c5b400dc8163
Revises: 7a5a548bfc37
Create Date: 2025-01-09 23:29:52.160689

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c5b400dc8163'
down_revision = '7a5a548bfc37'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
