"""init

Revision ID: c5b6559d5fd0
Revises: aa614c8c3de1
Create Date: 2025-02-19 00:03:35.310946

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c5b6559d5fd0"
down_revision = "aa614c8c3de1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
