"""init

Revision ID: c61bfee190ee
Revises: 9ebfec5748db
Create Date: 2024-08-30 15:28:48.814749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61bfee190ee'
down_revision = '9ebfec5748db'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
