"""init

Revision ID: c670a380df0d
Revises: 1b66a6efb354
Create Date: 2025-02-09 22:13:39.241818

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c670a380df0d"
down_revision = "1b66a6efb354"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
