"""init

Revision ID: c67ff4fecb9d
Revises: c24a690f43ff
Create Date: 2025-02-03 23:51:52.400056

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c67ff4fecb9d'
down_revision = 'c24a690f43ff'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
