"""init

Revision ID: c71410fb48f0
Revises: 121192299fe4
Create Date: 2025-02-10 15:35:20.686349

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c71410fb48f0"
down_revision = "121192299fe4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
