"""init

Revision ID: c7715ef543a2
Revises: 0d9354cef347
Create Date: 2025-01-30 23:54:16.190197

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c7715ef543a2"
down_revision = "0d9354cef347"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
