"""init

Revision ID: c782ce74333b
Revises: 0072c3016538
Create Date: 2025-01-30 21:48:24.046506

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c782ce74333b'
down_revision = '0072c3016538'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
