"""init

Revision ID: c7bacfcc7a47
Revises: f8e839593611
Create Date: 2025-01-24 01:36:34.147429

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c7bacfcc7a47'
down_revision = 'f8e839593611'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
