"""init

Revision ID: c8866c155f2c
Revises: 2508c69cc3cd
Create Date: 2025-01-09 00:27:25.092001

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c8866c155f2c"
down_revision = "2508c69cc3cd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
