"""init

Revision ID: c89b859eda8f
Revises: 909afcad5041
Create Date: 2024-10-16 10:34:06.088681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89b859eda8f'
down_revision = '909afcad5041'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
