"""init

Revision ID: c8a957811db8
Revises: 01baadbb3afe
Create Date: 2025-01-10 01:33:18.753906

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c8a957811db8'
down_revision = '01baadbb3afe'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
