"""init

Revision ID: c998e23b59da
Revises: cad47ac91b7a
Create Date: 2025-01-09 17:54:49.696462

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "c998e23b59da"
down_revision = "cad47ac91b7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
