"""init

Revision ID: ca5dc2beaff2
Revises: b2ba0760a640
Create Date: 2024-09-11 00:47:53.429389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5dc2beaff2'
down_revision = 'b2ba0760a640'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
