"""init

Revision ID: cac219bb7da2
Revises: c7715ef543a2
Create Date: 2025-01-30 23:55:07.331836

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cac219bb7da2'
down_revision = 'c7715ef543a2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
