"""init

Revision ID: cad47ac91b7a
Revises: 49a807c27220
Create Date: 2025-01-09 17:40:11.702174

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cad47ac91b7a'
down_revision = '49a807c27220'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
