"""init

Revision ID: cba36b6a5e85
Revises: 3cb652104ca8
Create Date: 2025-01-09 23:12:52.104951

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cba36b6a5e85'
down_revision = '3cb652104ca8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
