"""init

Revision ID: cbb840987dca
Revises: 1531f5ce2d07
Create Date: 2024-09-12 21:42:14.825932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb840987dca'
down_revision = '1531f5ce2d07'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
