"""init

Revision ID: cc401e9283e0
Revises: 9de5fbaf0080
Create Date: 2025-01-09 23:17:08.956385

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "cc401e9283e0"
down_revision = "9de5fbaf0080"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
