"""init

Revision ID: cc7102bb334b
Revises: 782c22483c37
Create Date: 2024-09-12 23:03:44.716243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7102bb334b'
down_revision = '782c22483c37'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
