"""init

Revision ID: ccb7f8485d03
Revises: 52284a828a09
Create Date: 2024-09-12 22:03:14.556609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb7f8485d03'
down_revision = '52284a828a09'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
