"""init

Revision ID: ccde87c249cc
Revises: a365452e5104
Create Date: 2025-01-09 17:27:10.107306

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "ccde87c249cc"
down_revision = "a365452e5104"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
