"""init

Revision ID: cd1eb961aa2b
Revises: 6b6676c263fe
Create Date: 2025-02-18 14:03:48.192223

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cd1eb961aa2b'
down_revision = '6b6676c263fe'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
