"""init

Revision ID: cd6820a7c91f
Revises: 9d6ab8891731
Create Date: 2025-02-04 17:16:37.593328

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "cd6820a7c91f"
down_revision = "9d6ab8891731"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
