"""init

Revision ID: ceda782dd3c6
Revises: b92cc04fa8e0
Create Date: 2024-09-11 00:14:11.319094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceda782dd3c6'
down_revision = 'b92cc04fa8e0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
