"""init

Revision ID: cfe73aa437ec
Revises: a14d45979beb
Create Date: 2025-01-24 22:31:57.774682

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'cfe73aa437ec'
down_revision = 'a14d45979beb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
