"""init

Revision ID: d05d780bf056
Revises: cfe73aa437ec
Create Date: 2025-01-24 23:15:27.123290

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd05d780bf056'
down_revision = 'cfe73aa437ec'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
