"""init

Revision ID: d0a11b37c7a2
Revises: 54cff6794dd2
Create Date: 2025-01-08 21:56:51.952210

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd0a11b37c7a2'
down_revision = '54cff6794dd2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
