"""init

Revision ID: d0dd1138ff54
Revises: 6888125f30ac
Create Date: 2025-01-08 23:17:18.538707

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd0dd1138ff54'
down_revision = '6888125f30ac'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
