"""init

Revision ID: d126a1e82cf3
Revises: ff51d78d54c7
Create Date: 2025-01-09 10:43:52.351154

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "d126a1e82cf3"
down_revision = "ff51d78d54c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
