"""init

Revision ID: d1ac82ee129f
Revises: 37b174202e6f
Create Date: 2025-01-25 00:34:40.273226

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd1ac82ee129f'
down_revision = '37b174202e6f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
