"""init

Revision ID: d273c567d270
Revises: 9e0bd2fb80bd
Create Date: 2025-01-25 04:02:44.854091

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "d273c567d270"
down_revision = "9e0bd2fb80bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
