"""init

Revision ID: d341cfc93e3c
Revises: 417910c62bf1
Create Date: 2025-01-09 16:30:49.849456

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd341cfc93e3c'
down_revision = '417910c62bf1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
