"""init

Revision ID: d3d93f30e3c8
Revises: 32fd0f6f24af
Create Date: 2025-02-01 20:37:45.033975

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd3d93f30e3c8'
down_revision = '32fd0f6f24af'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
