"""init

Revision ID: d448ce5d3071
Revises: f3f49904d64a
Create Date: 2025-02-03 22:06:46.330372

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd448ce5d3071'
down_revision = 'f3f49904d64a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
