"""init

Revision ID: d49d861a6b1d
Revises: 2b2bb4f5e8c1
Create Date: 2025-01-23 03:48:41.550623

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "d49d861a6b1d"
down_revision = "2b2bb4f5e8c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
