"""init

Revision ID: d4b00110fb04
Revises: 0768fc076f1d
Create Date: 2025-01-20 14:08:35.455696

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "d4b00110fb04"
down_revision = "0768fc076f1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
