"""init

Revision ID: d4c45344edca
Revises: e0f768fa83e5
Create Date: 2025-11-25 20:40:35.444719

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd4c45344edca'
down_revision = 'e0f768fa83e5'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
