"""init

Revision ID: d57bf6418444
Revises: b11ace1f2e7e
Create Date: 2024-10-16 00:56:16.826078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57bf6418444'
down_revision = 'b11ace1f2e7e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
