"""init

Revision ID: d61a59297f64
Revises: 436e72bb2e5b
Create Date: 2025-02-01 21:39:02.765493

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "d61a59297f64"
down_revision = "436e72bb2e5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
