"""init

Revision ID: d6e27de69e13
Revises: e8a7b746d7bf
Create Date: 2025-01-24 00:53:43.129094

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "d6e27de69e13"
down_revision = "e8a7b746d7bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
