"""init

Revision ID: d80eace7193e
Revises: 21d1eb8cf122
Create Date: 2025-02-02 00:25:08.084175

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "d80eace7193e"
down_revision = "21d1eb8cf122"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
