"""init

Revision ID: d8ab81a66b6f
Revises: 4c7c4ff5c81c
Create Date: 2024-09-13 21:36:12.427175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ab81a66b6f'
down_revision = '4c7c4ff5c81c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
