"""init

Revision ID: d9914d9daa9e
Revises: c3199fec875f
Create Date: 2025-02-01 23:54:36.391830

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'd9914d9daa9e'
down_revision = 'c3199fec875f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
