"""init

Revision ID: daacce55ad16
Revises: 85c48d2dbda4
Create Date: 2025-02-18 15:19:11.941970

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "daacce55ad16"
down_revision = "85c48d2dbda4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
