"""init

Revision ID: dacfdf1ebf72
Revises: 073187d337a2
Create Date: 2025-02-03 22:31:32.485182

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "dacfdf1ebf72"
down_revision = "073187d337a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
