"""init

Revision ID: db9cc88b0abb
Revises: f6f283f6a274
Create Date: 2025-01-09 10:52:44.741444

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'db9cc88b0abb'
down_revision = 'f6f283f6a274'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
