"""init

Revision ID: dc5eeb55bc74
Revises: 6cb953e35a25
Create Date: 2025-02-09 07:38:30.198189

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "dc5eeb55bc74"
down_revision = "6cb953e35a25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
