"""init

Revision ID: dc8d91bc5d8d
Revises: 274bcb096222
Create Date: 2025-01-20 15:30:58.812192

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "dc8d91bc5d8d"
down_revision = "274bcb096222"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
