"""init

Revision ID: dca0309ac327
Revises: 57b4d44bb11f
Create Date: 2024-09-13 19:04:08.554426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca0309ac327'
down_revision = '57b4d44bb11f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
