"""init

Revision ID: dd077bd4390e
Revises: 2539540f7564
Create Date: 2025-02-18 14:21:01.053499

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "dd077bd4390e"
down_revision = "2539540f7564"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
