"""init

Revision ID: dd2a724a1727
Revises: 36d1bcee4a1b
Create Date: 2025-10-13 18:35:00.683224

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "dd2a724a1727"
down_revision = "36d1bcee4a1b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
