"""init

Revision ID: de1d7d12f4c1
Revises: ccb7f8485d03
Create Date: 2024-09-12 22:07:18.563338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1d7d12f4c1'
down_revision = 'ccb7f8485d03'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
