"""init

Revision ID: e09b3803ed26
Revises: 22d68e075a91
Create Date: 2025-02-02 00:34:43.389826

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e09b3803ed26'
down_revision = '22d68e075a91'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
