"""init

Revision ID: e0bbc80a115c
Revises: 18af478efcef
Create Date: 2025-01-25 03:30:54.064121

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e0bbc80a115c'
down_revision = '18af478efcef'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
