"""init

Revision ID: e0f768fa83e5
Revises: e328aa3363a8
Create Date: 2025-11-25 20:36:33.575813

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e0f768fa83e5'
down_revision = 'e328aa3363a8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
