"""init

Revision ID: e213bfab7a8b
Revises: b6dd43cd6b09
Create Date: 2025-01-11 03:40:00.222568

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e213bfab7a8b"
down_revision = "b6dd43cd6b09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
