"""init

Revision ID: e21ba14319a6
Revises: 1021effda28d
Create Date: 2025-01-09 15:39:17.280783

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e21ba14319a6"
down_revision = "1021effda28d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
