"""init

Revision ID: e2539bf65d0e
Revises: 9bf761e86e79
Create Date: 2025-02-01 22:56:10.627072

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e2539bf65d0e"
down_revision = "9bf761e86e79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
