"""init

Revision ID: e2a821f38c15
Revises: 1a7257306482
Create Date: 2025-01-20 15:56:25.199818

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e2a821f38c15'
down_revision = '1a7257306482'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
