"""init

Revision ID: e328aa3363a8
Revises: c13ce71aada3
Create Date: 2025-11-25 20:33:22.999095

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e328aa3363a8'
down_revision = 'c13ce71aada3'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
