"""init

Revision ID: e37372e6d498
Revises: 6fede69cc080
Create Date: 2025-02-10 15:02:48.819611

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e37372e6d498"
down_revision = "6fede69cc080"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
