"""init

Revision ID: e412aceb1c04
Revises: fae80903f420
Create Date: 2024-08-28 12:00:22.285448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e412aceb1c04'
down_revision = 'fae80903f420'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
