"""init

Revision ID: e42933f4af07
Revises: d0dd1138ff54
Create Date: 2025-01-08 23:21:43.263600

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e42933f4af07"
down_revision = "d0dd1138ff54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
