"""init

Revision ID: e43f4f723de7
Revises: 0a7032c2c13a
Create Date: 2025-02-08 17:45:04.238127

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e43f4f723de7"
down_revision = "0a7032c2c13a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
