"""init

Revision ID: e4efe45c27b8
Revises: eadf6c7791c2
Create Date: 2025-01-23 23:39:52.491807

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e4efe45c27b8'
down_revision = 'eadf6c7791c2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
