"""init

Revision ID: e5193a9be12f
Revises: 02386d351c43
Create Date: 2025-01-09 02:01:08.855858

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e5193a9be12f"
down_revision = "02386d351c43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
