"""init

Revision ID: e647be2cae4e
Revises: a821ea323b4d
Create Date: 2025-02-19 00:14:47.461363

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e647be2cae4e"
down_revision = "a821ea323b4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
