"""init

Revision ID: e773f9f92da4
Revises: b85aab293e6a
Create Date: 2025-01-24 23:30:20.403065

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e773f9f92da4'
down_revision = 'b85aab293e6a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
