"""init

Revision ID: e7e6b7f24d9b
Revises: e647be2cae4e
Create Date: 2025-09-23 23:59:49.927549

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e7e6b7f24d9b'
down_revision = 'e647be2cae4e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
