"""init

Revision ID: e830c0365eae
Revises: 130245c0d700
Create Date: 2025-01-25 01:21:55.334251

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "e830c0365eae"
down_revision = "130245c0d700"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
