"""init

Revision ID: e88552d592c1
Revises: 60dc6346385c
Create Date: 2025-01-31 00:06:59.335856

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e88552d592c1'
down_revision = '60dc6346385c'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
