"""init

Revision ID: e8a7b746d7bf
Revises: 33205ef3c005
Create Date: 2025-01-24 00:51:28.757122

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'e8a7b746d7bf'
down_revision = '33205ef3c005'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
