"""init

Revision ID: eacf7d653d7e
Revises: bf0304a642e0
Create Date: 2025-01-11 03:56:23.303614

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'eacf7d653d7e'
down_revision = 'bf0304a642e0'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
