"""init

Revision ID: eadf6c7791c2
Revises: b5e29000373b
Create Date: 2025-01-23 23:31:46.341360

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'eadf6c7791c2'
down_revision = 'b5e29000373b'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
