"""init

Revision ID: eafcdbc4b3c6
Revises: 79448ac31888
Create Date: 2025-01-25 01:09:41.640195

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "eafcdbc4b3c6"
down_revision = "79448ac31888"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
