"""init

Revision ID: eb231cf49a64
Revises: 081626883c8d
Create Date: 2025-02-03 22:19:43.442921

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'eb231cf49a64'
down_revision = '081626883c8d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
