"""init

Revision ID: eb6b0bcaf6f6
Revises: 53a641ad877a
Create Date: 2025-02-02 01:16:23.577371

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'eb6b0bcaf6f6'
down_revision = '53a641ad877a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
