"""init

Revision ID: eb72acefee99
Revises: 5759af78b2db
Create Date: 2025-01-25 02:56:28.103193

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "eb72acefee99"
down_revision = "5759af78b2db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
