"""init

Revision ID: eb8d754593c5
Revises: 9b0d523f4784
Create Date: 2025-01-24 16:33:52.331517

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'eb8d754593c5'
down_revision = '9b0d523f4784'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
