"""init

Revision ID: ed2b1ac715bb
Revises: 9c8e7ca9d79e
Create Date: 2025-11-25 18:20:59.976953

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ed2b1ac715bb'
down_revision = '9c8e7ca9d79e'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
