"""init

Revision ID: edd0479f11cf
Revises: edee1ea930a5
Create Date: 2025-01-12 01:57:49.937174

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "edd0479f11cf"
down_revision = "edee1ea930a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
