"""init

Revision ID: edd4ebed6c5b
Revises: c3adcea50658
Create Date: 2025-01-10 11:06:29.158178

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "edd4ebed6c5b"
down_revision = "c3adcea50658"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
