"""init

Revision ID: edee1ea930a5
Revises: c3ce9c4a1058
Create Date: 2025-01-12 01:28:25.376084

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "edee1ea930a5"
down_revision = "c3ce9c4a1058"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
