"""init

Revision ID: ee13542d8ab8
Revises: 7b73bf80b31e
Create Date: 2025-01-09 23:33:24.817317

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "ee13542d8ab8"
down_revision = "7b73bf80b31e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
