"""init

Revision ID: eebc766fc380
Revises: aca84ab94b27
Create Date: 2025-01-12 13:08:03.129155

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'eebc766fc380'
down_revision = 'aca84ab94b27'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
