"""init

Revision ID: eebd40dc289a
Revises: f0e907d5f459
Create Date: 2025-01-23 22:47:16.615088

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "eebd40dc289a"
down_revision = "f0e907d5f459"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
