"""init

Revision ID: ef182f74c97c
Revises: 072b1906c384
Create Date: 2025-02-19 00:07:25.465087

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ef182f74c97c'
down_revision = '072b1906c384'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
