"""init

Revision ID: f0e907d5f459
Revises: fe937ae17cfc
Create Date: 2025-01-23 22:36:51.020240

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f0e907d5f459'
down_revision = 'fe937ae17cfc'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
