"""init

Revision ID: f0f71caaba5a
Revises: ca5dc2beaff2
Create Date: 2024-09-11 00:56:09.189549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f71caaba5a'
down_revision = 'ca5dc2beaff2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
