"""init

Revision ID: f10cd42028ae
Revises: b28c90526e12
Create Date: 2025-02-02 01:24:26.258058

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "f10cd42028ae"
down_revision = "b28c90526e12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
