"""init

Revision ID: f2167c6382c8
Revises: 25ef3ff9bf8c
Create Date: 2025-01-23 22:25:39.428958

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "f2167c6382c8"
down_revision = "25ef3ff9bf8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
