"""init

Revision ID: f2fb5eb7dc30
Revises: 5ac500f3aed6
Create Date: 2025-01-09 13:35:37.662937

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f2fb5eb7dc30'
down_revision = '5ac500f3aed6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
