"""init

Revision ID: f3437cec5a02
Revises: 3e571551f5c5
Create Date: 2025-02-01 20:54:38.678946

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "f3437cec5a02"
down_revision = "3e571551f5c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
