"""init

Revision ID: f375e314f886
Revises: 41c25e977908
Create Date: 2024-09-13 19:22:20.325601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f375e314f886'
down_revision = '41c25e977908'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
