"""init

Revision ID: f3884d0d02b4
Revises: e0bbc80a115c
Create Date: 2025-01-25 03:34:56.018212

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "f3884d0d02b4"
down_revision = "e0bbc80a115c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
