"""init

Revision ID: f3e3c6374747
Revises: 74462cdfa742
Create Date: 2025-02-10 15:41:01.076222

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "f3e3c6374747"
down_revision = "74462cdfa742"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
