"""init

Revision ID: f3f49904d64a
Revises: 4c0dc094f8b9
Create Date: 2025-02-03 22:02:21.557290

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "f3f49904d64a"
down_revision = "4c0dc094f8b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
