"""init

Revision ID: f41bcb9cb1d4
Revises: 26af00a9d7d2
Create Date: 2025-01-24 16:15:19.051396

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "f41bcb9cb1d4"
down_revision = "26af00a9d7d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_product",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.add_column("goods", sa.Column("user_product_id", sa.UUID(), nullable=True))
    op.drop_constraint("goods_product_id_fkey", "goods", type_="foreignkey")
    op.create_foreign_key(None, "goods", "user_product", ["user_product_id"], ["id"])
    op.drop_column("goods", "product_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goods", sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "goods", type_="foreignkey")
    op.create_foreign_key(
        "goods_product_id_fkey", "goods", "product", ["product_id"], ["id"]
    )
    op.drop_column("goods", "user_product_id")
    op.drop_table("user_product")
    # ### end Alembic commands ###
