"""init

Revision ID: f42949724ba9
Revises: 0d797d97f5a2
Create Date: 2025-01-09 23:45:38.735155

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f42949724ba9'
down_revision = '0d797d97f5a2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
