"""init

Revision ID: f452fdd6b6e7
Revises: 6b1323932989
Create Date: 2025-01-17 18:31:57.919069

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f452fdd6b6e7'
down_revision = '6b1323932989'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
