"""init

Revision ID: f45899ab5689
Revises: 8dd887a39b71
Create Date: 2025-02-18 13:47:42.784951

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f45899ab5689'
down_revision = '8dd887a39b71'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
