"""init

Revision ID: f46f6c2bbe03
Revises: 8bb87cbc2f04
Create Date: 2025-02-10 18:07:05.605540

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f46f6c2bbe03'
down_revision = '8bb87cbc2f04'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
