"""init

Revision ID: f5a7193a7d8d
Revises: a42021f0ca06
Create Date: 2025-01-24 03:20:54.645694

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f5a7193a7d8d'
down_revision = 'a42021f0ca06'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
