"""init

Revision ID: f661c43fff6e
Revises: d448ce5d3071
Create Date: 2025-02-03 22:09:52.800442

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f661c43fff6e'
down_revision = 'd448ce5d3071'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
