"""init

Revision ID: f66b3cc0bdd6
Revises: a75f424d34fd
Create Date: 2025-02-18 14:16:58.458310

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f66b3cc0bdd6'
down_revision = 'a75f424d34fd'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
