"""init

Revision ID: f6e72c76f3e4
Revises: e37372e6d498
Create Date: 2025-02-10 15:24:59.994939

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f6e72c76f3e4'
down_revision = 'e37372e6d498'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
