"""init

Revision ID: f6f283f6a274
Revises: 88b82b3a38de
Create Date: 2025-01-09 10:49:19.814438

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "f6f283f6a274"
down_revision = "88b82b3a38de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
