"""init

Revision ID: f7d4b60e8b0d
Revises: c26eb3dcc0db
Create Date: 2025-01-23 23:04:53.463138

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f7d4b60e8b0d'
down_revision = 'c26eb3dcc0db'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
