"""init

Revision ID: f8e839593611
Revises: 6e6fc288cc88
Create Date: 2025-01-24 01:35:41.444645

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f8e839593611'
down_revision = '6e6fc288cc88'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
