"""init

Revision ID: f93134c82a6a
Revises: 738a3b9725fb
Create Date: 2025-02-10 16:15:54.264299

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f93134c82a6a'
down_revision = '738a3b9725fb'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
