"""init

Revision ID: f981fae8e5b8
Revises: 2a5351887229
Create Date: 2024-08-30 14:12:22.224737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f981fae8e5b8'
down_revision = '2a5351887229'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
