"""init

Revision ID: fa9c69993c78
Revises: 31e5b914cbba
Create Date: 2025-01-11 03:29:52.996556

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fa9c69993c78'
down_revision = '31e5b914cbba'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
