"""init

Revision ID: fae80903f420
Revises: a95721b9c68a
Create Date: 2024-08-27 18:13:06.111967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae80903f420'
down_revision = 'a95721b9c68a'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
