"""init

Revision ID: fb24783e700f
Revises: e773f9f92da4
Create Date: 2025-01-24 23:35:25.741888

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fb24783e700f'
down_revision = 'e773f9f92da4'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
