"""init

Revision ID: fb92d1649a89
Revises: f3e3c6374747
Create Date: 2025-02-10 15:42:00.033388

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "fb92d1649a89"
down_revision = "f3e3c6374747"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
