"""init

Revision ID: fd2cc60defae
Revises: 41b5bd989bc2
Create Date: 2025-01-11 04:23:56.379675

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fd2cc60defae'
down_revision = '41b5bd989bc2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
