"""init

Revision ID: fdf45c5ac25b
Revises: 35a82a9fe4a8
Create Date: 2025-01-24 01:16:29.093500

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "fdf45c5ac25b"
down_revision = "35a82a9fe4a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
