"""init

Revision ID: fe937ae17cfc
Revises: 6a2b39280e87
Create Date: 2025-01-23 22:35:56.451715

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "fe937ae17cfc"
down_revision = "6a2b39280e87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
