"""init

Revision ID: fee8dff2fdc7
Revises: aa2af13e5566
Create Date: 2025-02-03 21:43:29.951761

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "fee8dff2fdc7"
down_revision = "aa2af13e5566"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
