"""init

Revision ID: ff161c9d1cd3
Revises: a552303de69a
Create Date: 2025-02-10 15:29:31.350072

"""

import sqlalchemy as sa
from alembic import op

# import geoalchemy2


# revision identifiers, used by Alembic.
revision = "ff161c9d1cd3"
down_revision = "a552303de69a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
