"""init

Revision ID: ff51d78d54c7
Revises: 31fd3ccbb760
Create Date: 2025-01-09 02:26:06.360671

"""
from alembic import op
import sqlalchemy as sa
# import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ff51d78d54c7'
down_revision = '31fd3ccbb760'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
