"""init

Revision ID: ff88cd94f99b
Revises: 8ca7cd7efe29
Create Date: 2024-09-11 01:48:59.252900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff88cd94f99b'
down_revision = '8ca7cd7efe29'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
