"""init

Revision ID: fffcbb0f69c5
Revises: a868408566df
Create Date: 2024-09-13 21:13:08.632643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffcbb0f69c5'
down_revision = 'a868408566df'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
