apiVersion: v1
kind: Pod
metadata:
  name: tmp-upload
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /mnt/shared
  volumes:
  - name: shared-data
    persistentVolumeClaim:
      claimName: shared-data-pvc
