apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        envFrom:
          - configMapRef:
              name: qracun-config
          - secretRef:
              name: qracun-secret
        env:
          - name: PGADMIN_CONFIG_PATH_PREFIX
            value: /pgadmin
          - name: PGADMIN_CONFIG_FORCE_SCRIPT_NAME
            value: /pgadmin
          - name: PGADMIN_ENABLE_PATH_PREFIX
            value: "True"
        ports:
        - containerPort: 80
