grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    port: 3000
    nodePort: 30832
  ingress:
    enabled: false

loki:
  enabled: true
  podSecurityPolicy:
    enabled: false
  persistence:
    enabled: true
    size: 5Gi
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
  singleBinary:
    replicas: 1

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push  # адрес Loki сервиса внутри кластера
    positions:
      filename: /run/promtail/positions.yaml  # файл для хранения позиции чтения логов
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container