grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: false

loki:
  enabled: true
  
  # Отключаем deprecated возможности
  podSecurityPolicy:
    enabled: false
  
  # НЕ используем config на верхнем уровне!
  # Вместо этого используем loki.config или отдельные секции
  
  loki:
    # Основные настройки
    auth_enabled: false
    
    # Настройки сервера
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    
    # Настройки memberlist для clustering
    memberlistConfig:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
        - loki-memberlist
    
    # Настройки ingester
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 1h
      max_chunk_age: 1h
      chunk_target_size: 1048576
      chunk_retain_period: 30s
    
    # Настройки storage
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    
    # Настройки compactor
    compactor:
      working_directory: /loki/boltdb-shipper-compactor
      shared_store: filesystem
    
    # Лимиты
    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
  
  # Persistence для хранения данных
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: ""  # Используйте default storage class
  
  # Ресурсы для тестового окружения
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
  

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push  # адрес Loki сервиса внутри кластера
    positions:
      filename: /tmp/positions.yaml  # файл для хранения позиции чтения логов
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container