# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import grpc_client.grpc_pb2 as grpc__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RestApiGRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBillUrl = channel.unary_unary(
                '/RestApiGRPC/SendBillUrl',
                request_serializer=grpc__pb2.BillUrl.SerializeToString,
                response_deserializer=grpc__pb2.BillInfo.FromString,
                _registered_method=True)
        self.GetTotalSumm = channel.unary_unary(
                '/RestApiGRPC/GetTotalSumm',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=grpc__pb2.TotalSumm.FromString,
                _registered_method=True)


class RestApiGRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendBillUrl(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTotalSumm(self, request, context):
        """Sends another greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestApiGRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBillUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBillUrl,
                    request_deserializer=grpc__pb2.BillUrl.FromString,
                    response_serializer=grpc__pb2.BillInfo.SerializeToString,
            ),
            'GetTotalSumm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTotalSumm,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=grpc__pb2.TotalSumm.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RestApiGRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RestApiGRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RestApiGRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendBillUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RestApiGRPC/SendBillUrl',
            grpc__pb2.BillUrl.SerializeToString,
            grpc__pb2.BillInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTotalSumm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RestApiGRPC/GetTotalSumm',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__pb2.TotalSumm.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
