prometheus:
  service:
    type: NodePort
    nodePort: 30900
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: true

grafana:
  enabled: false  # Grafana уже общая, не создаём свою

alertmanager:
  service:
    type: NodePort
    nodePort: 30093
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: 'default'
    receivers:
      - name: 'default'
        email_configs:
          - to: 'you@example.com'
            from: 'alertmanager@example.com'
            smarthost: 'smtp.example.com:587'
            auth_username: 'alertmanager@example.com'
            auth_password: 'yourpassword'

additionalServiceMonitors:
  - name: qracun-api
    namespace: default
    selector:
      matchLabels:
        app: qracun-api
    endpoints:
      - port: http
        path: /metrics
        interval: 15s