prometheus:
  prometheusSpec:
    service:
      type: NodePort
      nodePort: 30900
    serviceMonitorSelectorNilUsesHelmValues: true

grafana:
  enabled: false  # Grafana уже общая, не создаём свою
