#TOKEN = '659006306:AAHIkFC53ayy67ToAUcRZflZrBDvKotp5IA'
#PATH_DB = 'test_qrscanner.db'
#TYPE_DB = 'sqlite'
LANG = 'rus'

TYPE_DB = 'pgsql'
PG_BATABASE = 'qrscanner_dev'
PG_HOST = 'localhost'
PG_PORT = '5432'
PG_USERNAME = 'qrscanadmin'
PG_PASSWORD = 'qrscanadmin'

#PG_BATABASE = 'bupnhtov'
#PG_HOST = 'manny.db.elephantsql.com'
#PG_PORT = '5432'
#PG_USERNAME = 'bupnhtov'
#PG_PASSWORD = 'GqOfl0MqSAoDyALNjLEvc8WDVzYLVpAf'
