{
 "title": "Generic Service",
 "description": "Simplifies monitoring services on Kubernetes. Shows container logs, availability, resource usage and HTTP and gRPC traffic.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "grpc_package",
    "label": "gRPC Package",
    "query": {
     "query": "label_values(grpc_server_requests_total{namespace=\"$namespace\",release=\"$service\"}, grpc_service)"
    }
   },
   {
    "name": "loglevel",
    "label": "Log level",
    "query": "label_values({namespace=\"$namespace\", container=\"$service\"}, level)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "description": "Logs reported by the main container (without sidecars)",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Messages",
   "type": "logs",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", container=\"$service\", level=~\"$loglevel\"}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Rate of log messages",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", container=\"$service\", level=~\"$loglevel\"}[10m])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "Average uptime of the service in the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  min(ceil(\n    kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=\"$service\"} /\n    kube_deployment_status_replicas{namespace=\"$namespace\",deployment=\"$service\"}\n  ))\n[$__range:1m]) or\navg_over_time(\n  min(ceil(\n    kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=\"$service\"} /\n    kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=\"$service\"}\n  ))\n[$__range:1m])"
    }
   ]
  },
  {
   "title": "Replicas healthy",
   "type": "state-timeline",
   "description": "Timeline showing when how many of the desired replicas were healthy",
   "gridPos": { "h": 3, "w": 10, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(deployment) (\n  kube_deployment_status_replicas_available{namespace=\"$namespace\",deployment=\"$service\"} /\n  kube_deployment_status_replicas{namespace=\"$namespace\",deployment=\"$service\"}\n) or\nmax by(statefulset) (\n  kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=\"$service\"} /\n  kube_statefulset_status_replicas{namespace=\"$namespace\",statefulset=\"$service\"}\n)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "description": "Timeline showing when container restarts occurred",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "clamp_max(increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\",container=\"$service\"}[$__rate_interval]) > 0, 1)"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "timeseries",
   "description": "Running versions (Docker image tags) over time.",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by(version) (label_replace(kube_pod_container_info{namespace=\"$namespace\",container=\"$service\"}, \"version\", \"$1\", \"image\", \".*:(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Memory usage of the main container (without sidecars)",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=\"$namespace\",container=\"$service\"}) != 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage of the main container (without sidecars)",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (pod) (increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\",container=\"$service\"}[$__rate_interval])) > bool 0)\n* min by(pod) (kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\",container=\"$service\"}) != 0\nor\nmax by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"$service\"}[$__rate_interval])) != 0",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\",container=\"$service\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Response times",
   "type": "heatmap",
   "description": "Distribution of response times as measured by ingress controller",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(le) (increase(nginx_ingress_controller_response_duration_seconds_bucket{exported_namespace=\"$namespace\",exported_service=\"$service\"}[$__rate_interval])) or\nsum by(le) (increase(istio_request_duration_milliseconds_bucket{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"source\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "description": "Request count by HTTP status code as measured by ingress controller",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "expr": "sum by(method, status) (rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\",exported_service=\"$service\"}[$__rate_interval])) or\nsum by(response_code) (rate(istio_requests_total{destination_service_namespace=\"$namespace\",destination_service_name=\"$service\",reporter=\"source\"}[$__rate_interval]))",
     "legendFormat": "{{method}}: {{status}}"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Methods + status codes",
   "type": "timeseries",
   "description": "Request count by gRPC method and status code",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "label_replace(\n  sum by(grpc_service, grpc_method, grpc_code) (\n    rate(grpc_server_requests_total{namespace=\"$namespace\",release=\"$service\"}[$__rate_interval])\n  ),\n  \"grpc_service\", \"$1\", \"grpc_service\", \"${grpc_package}(.*)\"\n) != 0 or\nlabel_replace(\n  sum by(grpc_service, grpc_method, grpc_code) (\n    rate(grpc_server_handled_total{namespace=\"$namespace\",release=\"$service\"}[$__rate_interval])\n  ),\n  \"grpc_service\", \"$1\", \"grpc_service\", \"${grpc_package}(.*)\"\n) != 0",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}: {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "description": "Number of gRPC responses with status codes other than OK",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(grpc_code) (increase(grpc_server_requests_total{namespace=\"$namespace\",release=\"$service\",grpc_code!=\"OK\"}[10m])) != 0 or\nsum by(grpc_code) (increase(grpc_server_handled_total{namespace=\"$namespace\",release=\"$service\",grpc_code!=\"OK\"}[10m])) != 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}