apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgbackrest-backup
spec:
  schedule: "0 2 * * *"  # каждый день в 2:00 ночи
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: pgbackrest
            image: perconalab/percona-pgbackrest:2.55.0
            envFrom:
              - secretRef:
                  name: qracun-secret
            volumeMounts:
              - name: pg-data
                mountPath: /var/lib/postgresql/data:ro
              - name: backups
                mountPath: /backups
            command: ["/bin/sh", "-c"]
            args:
              - pgbackrest --stanza=main backup
          volumes:
            - name: pg-data
              persistentVolumeClaim:
                claimName: pg-pvc
            - name: backups
              persistentVolumeClaim:
                claimName: pgbackrest-pvc
