apiVersion: v1
kind: ConfigMap  
metadata:
  name: pgbackrest-config
data:
  pgbackrest.conf: |
    [global]
    repo-path=/backups
    repo-retention-full=7
    repo-retention-diff=4
    
    compress-type=lz4
    compress-level=3
    
    process-max=2
    archive-async=y
    spool-path=/var/spool/pgbackrest
    
    log-level-console=info
    log-level-file=detail
    log-path=/var/log/pgbackrest
    
    [main]
    db-path=/var/lib/postgresql/data
    db-host=postgres
    db-port=5432
    db-user=postgres