apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgbackrest-backup
spec:
  schedule: "0 2 * * *"  # каждый день в 2:00 ночи
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: pgbackrest
            image: woblerr/pgbackrest:2.54.2-alpine-v0.34
            envFrom:
              - secretRef:
                  name: qracun-secret
            volumeMounts:
              - name: pg-data
                mountPath: /var/lib/postgresql/data
                readOnly: true
              - name: backups
                mountPath: /backups
            command: ["/bin/sh", "-c"]
            args:
              - pgbackrest --pg1-host=localhost --pg1-user=$POSTGRES_USER --pg1-db=postgres --stanza=main backup
          volumes:
            - name: pg-data
              persistentVolumeClaim:
                claimName: pg-pvc
            - name: backups
              persistentVolumeClaim:
                claimName: pgbackrest-pvc
