{
 "title": "PostgreSQL PGbouncer",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "port",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "db",
    "label": "Db",
    "query": "label_values(pgbouncer_databases_database_current_connections,database)"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "label_values(pgbouncer_up, hostname)"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Client active connections $db",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (pgbouncer_pools_client_active_connections{database=~\"$db\",hostname=~\"$hostname\"})"
    }
   ]
  },
  {
   "title": "Stats queries total $db",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc( sum ( rate(pgbouncer_stats_queries_total{database=~\"$db\",hostname=~\"$hostname\"}[1m]) ) )"
    }
   ]
  },
  {
   "title": "Database pool size.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (database,hostname) (pgbouncer_databases_database_pool_size{database=~\"$db\",hostname=~\"$hostname\"})",
     "legendFormat": "{{database}},{{hostname}}"
    }
   ]
  },
  {
   "title": "Databases database reserve pool size.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (database,hostname) (pgbouncer_databases_database_reserve_pool_size{database=~\"$db\",hostname=~\"$hostname\"})",
     "legendFormat": "{{database}},{{hostname}}"
    }
   ]
  },
  {
   "title": "Total Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database) ( rate(pgbouncer_stats_queries_duration_microseconds{database=~\"$db\",hostname=~\"$hostname\"}[1m]) ) )",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Stats queries $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database, hostname) ( rate(pgbouncer_stats_queries_duration_microseconds{database=~\"$db\",hostname=~\"$hostname\"}[1m]) ) )",
     "legendFormat": "{{ database }}, {{ hostname }}: Stats queries duration microseconds"
    },
    {
     "expr": "sort_desc( sum by (database, hostname) ( rate(pgbouncer_stats_waiting_duration_microseconds{database=~\"$db\",hostname=~\"$hostname\"}[1m]) ) ) ",
     "legendFormat": "{{ database }}, {{hostname}}: Stats waiting duration microseconds"
    }
   ]
  },
  {
   "title": "Transactions stats $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database, hostname) ( rate(pgbouncer_stats_transactions_duration_microseconds{database=~\"$db\",hostname=~\"$hostname\"}[1m]) ) )  ",
     "legendFormat": "{{ database }}, {{ hostname }}: Stats transactions duration microseconds"
    },
    {
     "expr": "sort_desc( sum by (database, hostname) ( rate(pgbouncer_stats_transactions_total{database=~\"$db\",hostname=~\"$hostname\"}[1m]) ) )",
     "legendFormat": "{{ database }}, {{ hostname }}: Stats transactions total"
    }
   ]
  },
  {
   "title": "Pgbouncer pools connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{database=~\"$db\", hostname=~\"$hostname\"}",
     "legendFormat": "{{ database }},{{hostname}}: Client active connections "
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$db\", hostname=~\"$hostname\"}",
     "legendFormat": "{{ database }},{{hostname}}: Client waiting connections"
    },
    {
     "expr": "pgbouncer_pools_server_active_connections{database=~\"$db\", hostname=~\"$hostname\"}",
     "legendFormat": "{{ database }},{{hostname}}: Server active connections"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{database=~\"$db\", hostname=~\"$hostname\"}",
     "legendFormat": "{{ database }},{{hostname}}: Server idle connections"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{database=~\"$db\", hostname=~\"$hostname\"}",
     "legendFormat": "{{ database }},{{hostname}}: Server used connections"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{database=~\"$db\", hostname=~\"$hostname\"}",
     "legendFormat": "{{ database }},{{hostname}}: Server testing connections"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{database=~\"$db\", hostname=~\"$hostname\"}",
     "legendFormat": "{{ database }},{{hostname}}: Server login connections"
    },
    {
     "expr": "pgbouncer_databases_database_current_connections{database=~\"$db\", hostname=~\"$hostname\"}",
     "legendFormat": "{{ database }},{{hostname}}: Database current connections"
    }
   ]
  },
  {
   "title": "Total of incoming / outgoing bytes $db",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc( sum by (database,hostname) ( rate(pgbouncer_stats_received_bytes_total{database=~\"$db\",hostname=~\"$hostname\"}[1m])*8 ) )",
     "legendFormat": "{{ database }}, {{ hostname }}: Stats received bytes total"
    },
    {
     "expr": "sort_desc( sum by (database,hostname) ( rate(pgbouncer_stats_sent_bytes_total{database=~\"$db\",hostname=~\"$hostname\"}[1m])*8 ) )",
     "legendFormat": "{{ database }}, {{ hostname }}: Stats sent bytes total"
    }
   ]
  }
 ]
}