# ==========================
# General settings
# ==========================
replicaCount: 1

# =========================
# Ingress
# =========================
ingress:
  enabled: true
  className: nginx
  host: test.qracun.me
  tlsSecretName: test-qracun-tls
  clusterIssuer: letsencrypt-test
  annotations:
    sslRedirect: "true"
    forceSslRedirect: "true"
    hsts: "true"
    hstsMaxAge: "31536000"
    hstsIncludeSubdomains: "true"
    hstsPreload: "true"
  paths:
    api:
      serviceName: api
      servicePort: 80
      path: /api
    docs:
      serviceName: api
      servicePort: 80
      path: /docs
    frontend:
      serviceName: frontend
      servicePort: 80
      path: /

# ==========================
# API
# ==========================
api:
  replicas: 1
  image: ""
  service:
    type: ClusterIP
    ports:
      http: 
        port: 80
        targetPort: 80
        nodePort: 5553
      grpc:
        port: 50031
        targetPort: 
        nodePort: 55531

# ==========================
# Frontend
# ==========================
frontend:
  replicas: 1
  image: ""
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

# ==========================
# Telegram Bot
# ==========================
tgBot:
  replicas: 1
  image: ""

# ========================
# PostgresDB
# ========================
pg:
  enabled: true
  image: "postgres:17.5"
  replicas: 1
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
  mainPVC:
    storage: 15Gi
  backupPVC:
    storage: 5Gi

backup:
  schedule: "0 * * * *"
  gitUser: "Backup Bot"
  gitEmail: "backup@example.com"

# =========================
# PgAdmin
# =========================
pgadmin:
  replicas: 1
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: latest
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30831

# ==========================
# ImagePullSecrets
# ==========================
imagePullSecrets:
  - name: ghcr-secret

# ==========================
# ConfigMaps and Secrets
# ==========================
config:
  name: qracun-config
  TELEGRAM_LANGUAGES:
    - en
    - ru
  ALLOW_ORIGINS: 
    - https://test.qracun.me
  ALLOW_HEADERS:
    - "*"
  ALLOW_CREDENTIALS: true
  ALLOW_METHODS:
    - "*"
  DATABASE_DIALECT: postgresql
  DATABASE_DRIVER: psycopg2
  DATABASE_ECHO: true
  DATABASE_POOL_RECYCLE: 3600
  DATABASE_POOL_PRE_PING: true
  DATABASE_AUTO_FLUSH: false
  DATABASE_EXPIRE_ON_COMMIT: false

secrets:
  name: qracun-secret
  
# ==========================
# Cert-Manager / TLS
# ==========================
certManager:
  clusterIssuerName: letsencrypt-test
  email: qracun@proton.me
  http01:
    sslRedirect: false

# ====================
# mailTemplatesNFS
# ===================
mailTemplatesNFS:
  storage: 5Mi
  server: 10.1.166.0   # IP вашей виртуалки
  path: /exports/k8s/test_email_templates

# ====================
# logicBackupNFS
# ===================
logicBackupNFS:
  storage: 3Gi
  server: 10.1.166.0   # IP вашей виртуалки
  path: /exports/k8s/test_logic_backups

# ==========================
# ghcr-secret
# ==========================
ghcr:
  username: ""
  password: ""
  email: ""