# ==========================
# General settings
# ==========================
replicaCount: 1

# ==========================
# Images
# ==========================
images:
  api: ""
  frontend: ""
  tg: ""

# =========================
# Ingress
# =========================
ingress:
  enabled: true
  className: nginx
  host: test.qracun.me
  tlsSecretName: test-qracun-tls
  clusterIssuer: letsencrypt-test
  annotations:
    sslRedirect: "true"
    forceSslRedirect: "true"
    hsts: "true"
    hstsMaxAge: "31536000"
    hstsIncludeSubdomains: "true"
    hstsPreload: "true"
  paths:
    api:
      serviceName: api
      servicePort: 80
      path: /api
    docs:
      serviceName: api
      servicePort: 80
      path: /docs
    frontend:
      serviceName: frontend
      servicePort: 80
      path: /

# ==========================
# API
# ==========================
api:
  replicas: 1
  image: ""
  service:
    type: ClusterIP
    ports:
      http: 
        port: 80
        targetPort: 80
        nodePort: 5553
      grpc:
        port: 50031
        targetPort: 
        nodePort: 55531

# ==========================
# Frontend
# ==========================
frontend:
  replicas: 1
  service:
    type: ClusterIP
    port: 80

# ==========================
# Telegram Bot
# ==========================
tgBot:
  replicas: 1
  image: ""

# ========================
# PostgresDB
# ========================
pg:
  enabled: true
  image: "postgres:17.5"
  replicas: 1
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
  mainPVC:
    storage: 15Gi
  backupPVC:
    storage: 5Gi

backup:
  schedule: "0 * * * *"
  gitUser: "Backup Bot"
  gitEmail: "backup@example.com"

# =========================
# PgAdmin
# =========================
pgadmin:
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: latest
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 30831

# ==========================
# ImagePullSecrets
# ==========================
imagePullSecrets:
  - name: ghcr-secret

# ==========================
# ConfigMaps and Secrets
# ==========================
config:
  name: qracun-config
  DEBUG: ""
  INSTALL_DEV: ""
  TOKEN_EXPIRY_TIME_HOURS: ""
  FISCAL_SERVICE_HOSTNAME: ""
  FISCAL_SERVICE_URI: ""
  FISCAL_SERVICE_API_URI: ""
  TIME_LIFE_TEMP_LOGIN_LINK_MIN: ""
  FRONTEND_APP_LOGIN_LINK_PREFIX: ""
  FRONTEND_APP_VERIFY_LINK_PREFIX: ""
  REST_API_HOST: ""
  REST_API_PORT: ""
  REST_API_PREFIX: ""
  REST_API_TELEGRAM_ADMIN_CHAT_ID: ""
  DATABASE_DIALECT: ""
  DATABASE_DRIVER: ""
  DATABASE_ECHO: ""
  DATABASE_POOL_RECYCLE: ""
  DATABASE_POOL_PRE_PING: ""
  DATABASE_AUTO_FLUSH: ""
  DATABASE_EXPIRE_ON_COMMIT: ""
  UNICORN_HOST: ""
  UNICORN_PORT: ""
  UNICORN_LOG_LEVEL: ""
  UNICORN_RELOAD: ""
  UNICORN_WORKERS: ""
  ALLOW_ORIGINS: ""
  ALLOW_HEADERS: ""
  ALLOW_CREDENTIALS: ""
  ALLOW_METHODS: ""
  PGADMIN_DEFAULT_EMAIL: ""
  TELEGRAM_LANGUAGES: ""
  TELEGRAM_BOT_DEFAULT_LANG: ""
  TELEGRAM_ADMIN_CHAT_ID: ""
  TELEGRAM_GRPC_HOST: ""
  TELEGRAM_GRPC_PORT: ""
  TELEGRAM_WEBAPP_ADDRESS: ""
  TELEGRAM_QR_PIC_DIR: ""
  MASTER_EMAIL: ""
  SMTP_SERVER: ""
  SMTP_SERVER_PORT: ""
  EMAIL_REPLY_TO: ""
      

secrets:
  name: qracun-secret
  POSTGRES_HOST: ""
  POSTGRES_PORT: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: ""
  DATABASE_HOST: ""
  DATABASE_PORT: ""
  DATABASE_USER: ""
  DATABASE_PASSWORD: ""
  DATABASE_NAME: ""
  PGADMIN_DEFAULT_PASSWORD: ""
  TELEGRAM_BOT_TOKEN: ""
  REST_API_TELEGRAM_BOT_TOKEN: ""
  SECRET_KEY: ""
  SMTP_SERVER_PASSWORD: ""
  MAILERSEND_API_KEY: ""


# ==========================
# Cert-Manager / TLS
# ==========================
certManager:
  clusterIssuerName: letsencrypt-test
  email: qracun@proton.me
  http01:
    sslRedirect: false

# ====================
# mailTemplatesNFS
# ===================
mailTemplatesNFS:
  storage: 5Mi
  server: 192.168.168.10   # IP вашей виртуалки
  path: /exports/k8s/test_email_templates