export default {
  header: "About the qr_bill_app Application",
  text1: `This application is designed for collecting data on purchases 
        made by the user within the territory of Montenegro.`,
  text2: `The user can scan a QR code on receipts or invoices 
        generated by cash registers in Montenegro.`,
  text3: `This application works only with the QR code format 
        of Montenegrin receipts.`,
  text4: `Receipt details are retrieved by this application 
        through the Montenegrin fiscal service at: https://mapr.tax.gov.me/`,
  text5: `Once all the receipt data is saved, the user can 
        view various analytics on their purchases.`,
  capabilities: {
    header: "Features of qr_bill_app.me",
    text1: `✅ Receipt and invoice scanning – simply 
        point your camera at a QR code, and the app 
        will automatically save all the data.`,
    text2: `✅ Purchase categorization – create 
        your own categories, and the app will 
        remember and suggest them in the future.`,
    text3: `✅ Expense analytics – track your spending 
        by categories, stores, and individual products.`,
    text4: `✅ Price tracking – the app records 
        price changes for previously purchased items.`,
    text5: `✅ Security and privacy – 
        the app can be used anonymously, 
        without linking to banks or social networks.`,
    text6: `✅ Telegram bot – send receipt photos 
        or QR code links to qr_bill_app_bot and 
        quickly add them to the app.`,
    text7: `✅ Support for three languages – Russian, 
        English, Montenegrin.`
  },
  why: {
    header: "Features of the qr_bill_app.me:",
    text1: `✅ Unlike banking apps, qr_bill_app.me 
        allows tracking all expenses, including 
        cash payments and purchases in different stores.`,
    text2: `✅ It is an independent solution for those who want 
        to consciously manage their budget and analyze 
        their expenses in a convenient format.`,
    text3: `✅ The app is based on PWA (Progressive Web App) technology, 
        which means it can be installed on any device 
        that supports PWA-enabled browsers.`,
    text4: "✅ It can be installed without App Store or Google Play.",
    text5: "✅ It takes up minimal space on your device.",
    text6: `✅ Updates are released instantly, 
        without waiting for app store approvals.`

  },
  pwa: {
    header: "qr_bill_app.me is a PWA app, which means:",
    text1: "✅ It can be installed without App Store or Google Play.",
    text2: "✅ It takes up minimal space on your device.",
    text3: "✅ Works on any device with a browser.",
    text4: `✅ Updates are released instantly, 
        without waiting for app store approvals.`
  },
  security: {
    header: "Security and Privacy",
    text1: `🔒 Default anonymity:
        qr_bill_app.me does not require registration via bank accounts, 
        social networks, or email. You can create a fully 
        anonymous account with a unique login and password.`,
    text2: `📧 Access recovery (optional):
        If you want to secure your account, you can link 
        an email or Telegram. This will allow you to restore access 
        in case of a lost password. Your data remains with you and 
        is not shared with third parties.`,
    text3: `💾 Full control over data:
        You can delete your account at any time, along with 
        all purchases, receipts, and categories — without 
        the possibility of recovery.`,
    text4: "🔗 Encryption and data protection:",
    text5: "✅ All data is transmitted via a secure HTTPS protocol.",
    text6: "✅ Account access is protected by a login and password known only to you.",
    text7: "✅ The app does not share users' personal data with third-party services."
  },
  attention: {
    header: "Attention! The app is under development",
    text1: `❗ qr_bill_app.me is a project that is still evolving. 
        Errors, service interruptions, or data loss 
        may occur during its use. The administration does not 
        guarantee the security of the entered information.`,
    text2: `📌 The app is provided "as is" 
        (AS IS) — without guarantees of data security, stability, 
        or support. Use the service at your own risk.`,
    text3: `We strive to make qr_bill_app.me convenient and reliable, 
        but since the project is funded by voluntary 
        donations, its stability and development speed 
        depend on user support.`
  },
  contacts: {
    header: "Contacts",
    text1: `Stay updated with qr_bill_app.me news and updates! 
        Follow us on social media and ask questions in our chat.`,
    text2: "🔹 News channel:",
    text3: "🔹 Threads:",
    text4: "🔹 Instagram:",
    text5: "🔹 Feedback & discussions:",
    text6: "📩 For any inquiries, feel free to message us in the chat or on social media!",
    tg_chat: "Telegram-chat"
  }
};
