export default {
    header: "About the QRacun Application",
    text1: `This application is designed for collecting data on purchases 
            made by the user within the territory of Montenegro.`,
    text2: `The user can scan a QR code on receipts or invoices 
            generated by cash registers in Montenegro. 
            This application works only with the QR code format 
            of Montenegrin receipts.`,
    text3: `Receipt details are retrieved by this application 
            through the Montenegrin fiscal service at: https://mapr.tax.gov.me/`,
    text4: `Once all the receipt data is saved, the user can 
            view various analytics on their purchases.`
};
