name: Build and make test qr_bill_app

on:
  push:
    branches:
      - dev

env:
  NAMESPACE: qr_bill_app-test
  MAIN_CONF_NAME: qr_bill_app-config
  BASE_NAME_IMAGE_API: ${{ vars.TEST_NAME_IMAGE_API }}
  BASE_NAME_IMAGE_FRONTEND: ${{ vars.TEST_NAME_IMAGE_FRONTEND }}
  BASE_NAME_IMAGE_TELEGRAM_BOT: ${{ vars.TEST_NAME_IMAGE_TELEGRAM_BOT }}
     
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check changes in backend/rest_api
        id: rest_api_changed
        run: |
          OUTPUT=$( git diff HEAD\^ HEAD -- backend/rest_api | tail -1) &&
          echo "::set-output name=OUTPUT::$OUTPUT"
      - name: Check changes in backend/telegram_bot
        id: tg_changed
        run: |
          OUTPUT=$( git diff HEAD\^ HEAD -- backend/tg_bot | tail -1) &&
          echo "::set-output name=OUTPUT::$OUTPUT"
      - name: Check changes in frontend
        id: frontend_changes
        run: |
          OUTPUT=$( git diff HEAD\^ HEAD -- frontend | tail -1) &&
          echo "::set-output name=OUTPUT::$OUTPUT"
      - name: Build all images. 
        env:
          TEST_MODE: True
          NAME_IMAGE_API: ${{ env.BASE_NAME_IMAGE_API }}
        run: |
          mkdir -p backend/rest_api/grpc_proto;
          cp backend/grpc_proto/*.proto backend/rest_api/grpc_proto/;
          ls -la backend/rest_api/grpc_proto;
          mkdir -p backend/tg_bot/grpc_proto;
          cp backend/grpc_proto/*.proto backend/tg_bot/grpc_proto/;
          ls -la backend/tg_bot/grpc_proto;
          docker compose build api;
          docker compose build tg;
          docker compose build frontend;
      - name: start all docker containers for testing
        env:
          TEST_MODE: True
          NAME_IMAGE_API: ${{ env.BASE_NAME_IMAGE_API }}
          ALLOW_ORIGINS: ${{ vars.ALLOW_ORIGINS }}
          ALLOW_HEADERS: ${{ vars.ALLOW_HEADERS }}
          ALLOW_CREDENTIALS: ${{ vars.ALLOW_CREDENTIALS }}
          ALLOW_METHODS: ${{ vars.ALLOW_METHODS }}
          TOKEN_EXPIRY_TIME_HOURS: ${{ vars.TOKEN_EXPIRY_TIME_HOURS }}
          DATABASE_DIALECT: ${{ vars.DATABASE_DIALECT }}
          DATABASE_DRIVER: ${{ vars.DATABASE_DRIVER }}
          DATABASE_HOST: ${{ vars.DATABASE_HOST }}
          DATABASE_NAME: ${{ vars.DATABASE_NAME }}
          DATABASE_USER: ${{ vars.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ vars.DATABASE_PORT }}
          DATABASE_ECHO: ${{ vars.DATABASE_ECHO }}
          DATABASE_POOL_RECYCLE: ${{ vars.DATABASE_POOL_RECYCLE }}
          DATABASE_POOL_PRE_PING: ${{ vars.DATABASE_POOL_PRE_PING }}
          DATABASE_AUTO_FLUSH: ${{ vars.DATABASE_AUTO_FLUSH }}
          DATABASE_EXPIRE_ON_COMMIT: ${{ vars.DATABASE_EXPIRE_ON_COMMIT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REST_API_APP_NAME: ${{ vars.REST_API_APP_NAME }}
          REST_API_STATIC: ${{ vars.REST_API_STATIC }}
          REST_API_DOCS: ${{ vars.REST_API_DOCS }}
          REST_API_HOST: ${{ vars.REST_API_HOST }}
          REST_API_PORT: ${{ vars.REST_API_PORT }}
          REST_API_PREFIX: ${{ vars.REST_API_PREFIX }}
          MASTER_EMAIL: ${{ vars.MASTER_EMAIL }}
          SMTP_SERVER: ${{ vars.SMTP_SERVER }}
          SMTP_SERVER_PORT: ${{ vars.SMTP_SERVER_PORT }}
          SMTP_SERVER_PASSWORD: ${{ secrets.SMTP_SERVER_PASSWORD }}
          EMAIL_REPLY_TO: ${{ vars.EMAIL_REPLY_TO }}
          REST_API_LOGIN_LINK_URI: ${{ vars.REST_API_LOGIN_LINK_URI }}
          TIME_LIFE_TEMP_LOGIN_LINK_MIN: ${{ vars.TIME_LIFE_TEMP_LOGIN_LINK_MIN }}
        run: |
          docker compose up -d;
      - name: Run the Smoke Tests
        if: ${{ (steps.rest_api_changed.outputs.OUTPUT != '')}}
        run: |
          echo "Smoke Testing";
          docker compose exec -T api env;
          docker compose exec -T api bash -c scripts/./start_smoke_test.sh;
      - name: Run unittests for rest_api. 
        if: ${{ (steps.rest_api_changed.outputs.OUTPUT != '')}}
        run: |
          echo "Start Unit Tests";
          env PYTHONPATH=$PYTHONPATH:/src poetry run pytest /src/tests/app;
          # docker compose exec -T api bash -c scripts/./start_unit_tests.sh;