apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-promtail-custom
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  promtail.yaml: |
    server:
      log_level: info
      log_format: logfmt
      http_listen_port: 3101
    
    clients:
      - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
    
    positions:
      filename: /run/promtail/positions.yaml
    
    scrape_configs:
      - job_name: kubernetes-pods-{{ .Release.Namespace }}-only
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - {{ .Release.Namespace }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: {{ .Release.Namespace }}
          
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
    
    tracing:
      enabled: false